### ISSUE TITLE
Package 'Azure.Security.KeyVault.Secret's missing from ConfigurationBuilders.AzureAppConfiguration?

### ISSUE THREAD

**Issue by stilren** [aspnet/MicrosoftConfigurationBuilders#100]
I cannot get the new version of the azure app configuration handler to work - it seems to be missing a reference or something.

- Create a new project using the template ASP.NET Web Application (.NET Framework) => Web Api
- Install Microsoft.Configuration.ConfigurationBuilders.AzureAppConfiguration 1.0.0-rc Microsoft.Configuration.ConfigurationBuilders.Environment 2.0.0-rc System.Configuration.ConfigurationManager 4.7.0
- Add a endpoint to the AzureAppConfig builder in Web.config
- Add the builder to `"<appSettings` `configBuilders="AzureAppConfig">"`

It fails with the message "the assembly 'Azure.Security.KeyVault.Secrets, Version=4.0.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' could not be loaded."

If you manually install Azure.Security.KeyVault.Secrets the error message disappears but there is still a crash without a inner exception

Visual Studio 2019 Professional Version 4.7.03190
Following: https://docs.microsoft.com/sv-se/azure/azure-app-configuration/quickstart-dotnet-app

**Comment by StephenMolloy** [comment]
Shoot. That's an unfortunate omission from the nuspec file. Thanks for pointing it out.

Installing the package manually should address the issue though. Do you have any more details on the crash you encounter after installing the KeyVault.Secrets package?

**Comment by stilren** [comment]
I uploaded a api project scaffolded with visualstudio to my github: https://github.com/stilren/AppConfigCrashExample

Heres a picture of the crash message:
https://github.com/stilren/AppConfigCrashExample/blob/master/Error%20message.JPG

I have setup services using azure app configuration in .net framework earlier last year (which are running in production just fine). I have no idea why this is crashing now or how to debug it.

**Comment by stilren** [comment]
Im guessing nobody is looking at this? I figure I could debug it if I could build the project locally and use it in the project (but I have not been able to) or if I somehow get more information from the assembly that is failing.

**Comment by jimmyca15** [comment]
Hello @stilren in your example I see you are using the [connectionString attribute](https://github.com/stilren/AppConfigCrashExample/blob/8f50799b44246289e0979c054bcb7d5bb7a768de/WebApplication1/Web.config#L12).

With the latest version of the package, this was replaced with "endpoint" as described [here](https://github.com/aspnet/MicrosoftConfigurationBuilders#azureappconfigurationbuilder). Could you update the AzureAppConfiguration builder to use the parameter set required by the new package and see if the error still occurs?

It looks like in your pic the "details" link wasn't included. I'm not sure if it was left out or if the latest version of vs is not being used.


![image](https://user-images.githubusercontent.com/21000428/73200381-aad54680-4104-11ea-8428-c1e8107efc0d.png)

**Comment by stilren** [comment]
@jimmyca15 Thanks for the connectionString heads up. My problems persisted with endpoint though. I did not have a details link in my error message but I can see the stacktrace if I inspect the page.

So using the new AzureAppConfigurationHandler gives me the error message:
[RequestFailedException]: Service request failed.
Status: 403 (Forbidden)] 

I added another API to the repo using the older version of the handler and that works for me (https://github.com/stilren/AppConfigCrashExample)

I have unblocked myself by using the older version of the handler for the moment even though it would be nice to upgrade since we are in production with a few services already.

**Comment by jimmyca15** [comment]
Hello @stilren 

The 403 is due to the identity being used by the Azure App Configuration configuration builder not being assigned to neither the Azure App Configuration Data Reader or Azure App Configuration Data Owner roles.

We have an issue open to document the requirement for this role assignment here: #102 

I am glad that you are not blocked, and to make the migration easier we have an issue open to keep the `connectionString` attribute that you were using in the previous release #101. Connection string is a completely valid way to connect to Azure App Configuration.

**Comment by stilren** [comment]
@jimmyca15 
I can confirm that adding this the Azure App Configuration Data Reader solves my issues. Thanks!

**Comment by StephenMolloy** [comment]
#107
