### ISSUE TITLE
AzureAppConfigBuilder Bug: Users in group with App Configuration Data Reader not allowed access using config builder

### ISSUE THREAD

**Issue by stilren** [aspnet/MicrosoftConfigurationBuilders#112]
To repeat this bug:
1. Add a group with your user in it as a App Configuration Data Reader to your config
2. Run a project with a AzureAppConfigBuilder targeting this config
3. Access will be denied
4. Add App Configuration Data Reader to your user (wait 15 mins or so...)
5. Run a project with a AzureAppConfigBuilder targeting this config
6. Access will be granted

**Comment by StephenMolloy** [comment]
I believe this is a known issue with AAD group support in the App Configuration service. I saw an internal email thread about it earlier this week, but it looks like somebody has also opened a github issue (https://github.com/Azure/AppConfiguration/issues/281) for the App Configuration team today. I'm going to close this issue, as the work to fix this belongs to the App Configuration repo.

https://github.com/Azure/AppConfiguration/issues/281
