### ISSUE TITLE
DefaultAzureIdentity .. need ability to specify options for development/VS

### ISSUE THREAD

**Issue by logiclabs** [aspnet/MicrosoftConfigurationBuilders#117]
The DefaultAzureIdentity doesn't appear to work in a quite a few scenarios, so it would be great if options could be passed to it (perhaps using a serialized connection string, as was case before)

We use development VM's with VS2017/2019, running in Azure and some VM's have managed identities.  When developing, DefaultAzureIdentity will opt to use Environment, Managed Identity and then the MSAL SharedTokens in that order. We found we need to disable Managed Identity to access keyvault in our dev env (or specifically use SharedTokenCacheCredential instead), but then re-enable it for deployment.

There are also scenarios where you need to specify one credential or a tenant id, because there are.  I understand these can be done through environment variables, but that is not ideal in windows/IIS env's, and would be much nicer to be able to specify through config.

**Comment by logiclabs** [comment]
I know it's outside of the scope here, but just to add, DefaultAzureIdentity seems very broken at the moment from a developer point of view.. the VS integration (that did work) is not yet working, and AZ CLI support has only just been added, which helps a little in being able to provide dev credentials. 

For our own direct keyvault code, I've found using the latest version and logging onto AZ CLI is the only way to reliably use the developers credentials within VS 2017/2019.

**Comment by logiclabs** [comment]
I guess one option is to do something like the overrideable MapKeys() method.. Adding an overridable  factory method for creating the TokenCredential, and then developers can subclass and override, if they need to configure the credentials directly.

**Comment by twsouthwick** [comment]
@logiclabs I took a stab at a PR for this - you can also try updating to the latest version of Azure.Identity. The behavior of DefaultAzureTokenCredential gets better over time.
