### ISSUE TITLE
Cannot connect to Azure Key Vault anymore due to AKV10032 exception

### ISSUE THREAD

**Issue by Expecho** [aspnet/MicrosoftConfigurationBuilders#118]
Before v2 I could use a connection string when connecting to an Azure Keyvault. Doing local development I used "" as a connection string.

V2 throws an exception on using a connection string. But as soon as I remove it I cannot connect anymore due to the following exception:

AKV10032: Invalid issuer. Expected one of https://sts.windows.net/ [....] 

I have several subscriptions attached to my account and now it picks the wrong one. I used `az account set --subscription xxx` to set the correct subscription but even then it still does not work. How can I influence the connection string nowadays or how can I resolve this?

**Comment by StephenMolloy** [comment]
Are you saying you see this on your dev machine? Or does this reproduce in a deployed app on Azure?

I don't know a lot about the internal workings of the Key Vault and Azure Identity packages being leveraged here... but I'm guessing this is an Azure issue, and not an issue with the ConfigBuilders package. See https://github.com/Azure/azure-cli/issues/11871

I do not have a repro in front of me to test, but it sounds like changing your default subscription might be a workaround for the moment? Does [Select-AzureSubscription](https://docs.microsoft.com/en-us/powershell/module/servicemanagement/azure/select-azuresubscription?view=azuresmps-4.0.0) work to resolve your issue?

**Comment by Expecho** [comment]
I see this on my dev machine. Once deployed there is no problem. Using Select-AzureSubscription does not work either.

**Comment by Expecho** [comment]
Hi @StephenMolloy  no worries, I can understand things like shifted priorities and focus leads to less time for things like this.

I think the issue has to do with a combination of me having multiple accounts and visual studio not able to present the right credentials. I did some digging and lots of people do experience the same with other services as well so I think it is not related to this specific package.
