### ISSUE TITLE
EnvironmentConfigBuilder not supporting colon, and colons and underscores are common in appSettings keys

### ISSUE THREAD

**Issue by bplasmeijer** [aspnet/MicrosoftConfigurationBuilders#123]
Deploying to AKS we are not able to set the app settings values because colons are not [supported](https://github.com/kubernetes/kubernetes/issues/53201). 

The AzureKeyVaultConfigBuilder has a MapKey function where the colon is replaced with '-'

```
    public override string MapKey(string key)
        {
            if (String.IsNullOrEmpty(key))
                return key;

            // Colons and underscores are common in appSettings keys, but not allowed in key vault key names.
            // It's likely that apps will want to lookup config values with these characters in their name in
            // key vault. More extensive key mapping can be done with subclasses. But let's handle the most
            // most common case here.
            key = key.Replace(':', '-');
            key = key.Replace('_', '-');
            return key;
        }
```

I want to propose the same implementation as used in aspnetcore, https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#environment-variables

The ```:``` separator doesn't work with environment variable hierarchical keys on all platforms. ```_```, the double underscore, is:

- Supported by all platforms. For example, the ```:``` separator is not supported by Bash, but ```__``` is.
- Automatically replaced by a ```:```

**Comment by ivanff** [comment]
+1

**Comment by Expecho** [comment]
I think supporting this is vital. The way I see it this library is heavily used in lift and shift operations to run windows containers on AKS. We are in the process of doing this and not being able to use : in the web.config settings forces us to create workarounds that shouldn't be necessary.

**Comment by Expecho** [comment]
@StephenMolloy I do appreciate your involvement in this repo and understand the fact you're probably busy with lots of other interesting stuff but do you have any plans or a schedule concerning addressing issues and PR's in the (near) future?

**Comment by StephenMolloy** [comment]
#172 introduced a more flexible and generic way to handle character mapping across the board for config builders. You should be able to leverage the 'charMap' attribute to do this in the next release.
