### ISSUE TITLE
IIS Configuration Editor schema

### ISSUE THREAD

**Issue by D4ve0s** [aspnet/MicrosoftConfigurationBuilders#126]
Apologies if this is documented elsewhere. When using Configuration Builders with on-premise IIS the configuration editor displays an error related the configBuilders attribute unrecognised on appSettings element. Would it be possible to add some guidance in the documentation to add a schema file to add this configuration section and attribute to remove this error? 

![image](https://user-images.githubusercontent.com/40890443/80733034-10badb00-8b05-11ea-8ae3-2125147db71a.png)

example:
%systemroot%\system32\inetsrv\config\schema\configBuilders_schema.xml
`<configSchema>`
`  <sectionSchema name="appSettings">`
`      <attribute name="configBuilders" type="string"/>`
`  </sectionSchema>`
`</configSchema>`

**Comment by StephenMolloy** [comment]
[IIS Schema FAQ](../docs/FAQ.md#iisschema)
