### ISSUE TITLE
How to disable configuration builders?

### ISSUE THREAD

**Issue by bahman616** [aspnet/MicrosoftConfigurationBuilders#132]
I have added configuration builders (environment) to my legacy asp.net code so that I can containerise it using Windows Containers. However, I would still want to support the current non-containerised version of the app for some on-prem clients.  I would like to be able to turn the configuration builders off for on-prem clients. Because I don't have much control over their systems and they could add/remove environment variables at their own discretion. I wonder if there is a way to have configuration builders in place, but be able to toggle it off/on based on an app setting value?

**Comment by StephenMolloy** [comment]
#173 should help here.
