### ISSUE TITLE
Enable Application Insights not working

### ISSUE THREAD

**Issue by JCPuerto** [aspnet/MicrosoftConfigurationBuilders#138]
In a .NET Framework 4.7.2 web application deployed to an Azure App Service I have the option to _Enable Application Insights without redeploying your code_. This has been working properly until we started using Azure App Configuration.

![image](https://user-images.githubusercontent.com/10167695/90316235-dd069400-deee-11ea-90c8-bee7ab87d6df.png)

Our web.config looks like this:

```xml
<configBuilders>
    <builders>
      <add name="AzureAppConfig" mode="Greedy" connectionString="${AzureAppConfiguration}"
        type="Microsoft.Configuration.ConfigurationBuilders.AzureAppConfigurationBuilder, Microsoft.Configuration.ConfigurationBuilders.AzureAppConfiguration, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"/>
      <add name="Environment"
        type="Microsoft.Configuration.ConfigurationBuilders.EnvironmentConfigBuilder, Microsoft.Configuration.ConfigurationBuilders.Environment, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"/>
    </builders>
  </configBuilders>
  <appSettings configBuilders="Environment, AzureAppConfig">
    <add key="ApplicationName" value="MyApp"/>
    <!-- This config is defined here but the value is read from the Azure Application Settings. See image below  -->
    <add key="AzureAppConfiguration" />
    <!-- other configs here -->
  </appSettings>

```
**Before** turning on _Application Insights_, these are our Azure Application Settings:
![image](https://user-images.githubusercontent.com/10167695/90316362-a3825880-deef-11ea-8888-396a31a259fd.png)

**After** turning on _Application Insights_ it added at least 11 new settings:

![image](https://user-images.githubusercontent.com/10167695/90316428-1e4b7380-def0-11ea-9098-5bb5e2109052.png)

**But no telemetry is being sent to _Application Insights_.**

If we remove the `configBuilders="Environment, AzureAppConfig"` part then _Application Insights_ works properly!

What do we need to do in order to use _App Configuration_ **and** _Application Insights_ without modifying the code?

Thank you!

**Comment by StephenMolloy** [comment]
This might be a better question for the AppInsights team, as they will know the ins and outs of how exactly they get their stuff injected into the application. [As you've already surmised.](https://github.com/Azure/AppConfiguration/issues/392)

I do know that somewhere along the line, AppInsights goes through the environment. I suspect your 'Environment' config builder is conflicting with how they draw from environment variables somehow. You might try naming your config builder something different, or perhaps using a `prefix` filter on the builder to only read the 'AzureAppConfiguration' setting you're interested in and hopefully avoiding messing with the AppInsight settings.

Those are my best guesses. But like I said, the AppInsight team would better know what is going on here.

**Comment by StephenMolloy** [comment]
See [this comment](https://github.com/aspnet/MicrosoftConfigurationBuilders/issues/133#issuecomment-1049520479) on what I think is the same issue.
