### ISSUE TITLE
Please update to Azure.Identity 1.2 or newer

### ISSUE THREAD

**Issue by heaths** [aspnet/MicrosoftConfigurationBuilders#139]
https://github.com/aspnet/MicrosoftConfigurationBuilders/blob/22371104020c6540446f86f5102990ac7ed8f02c/src/Azure/Azure.csproj#L55-L60

Azure Identity 1.2 introduces the `VisualStudioCredential`, which allows VS integration services to work seemlessly once the developer logs into Visual Studio, as well as supporting production workloads as `DefaultAzureCredential` supports environment variables, MSI, Visual Studio, Azure CLI, and more.

**Comment by twsouthwick** [comment]
As a work around for now, users can manually pull in v1.2+ and get this functionality.

**Comment by heaths** [comment]
Yes, however the out-of-the-box experience is all UI-driven to support connecting to Key Vault. They won't know they need to add a newer version of Azure.Identity, or even what Azure.Identity is.

**Comment by StephenMolloy** [comment]
Fixed in #174
