### ISSUE TITLE
Error on application startup - Could not load file or assembly...

### ISSUE THREAD

**Issue by leniency** [aspnet/MicrosoftConfigurationBuilders#14]
I ran into a problem today testing out the 1.0 version of the Azure configuration builder package. It looks like something isn't signed right?

**Steps:**

1. Created a new blank ASP.Net project targeting .Net 4.7.1. I'm using 15.7.2
2. Installed nuget package for `Microsoft.Configuration.ConfigurationBuilders.Azure` - and all dependencies.
3. Started the app and immediately get the error "Could not load file or assembly 'Microsoft.Configuration.ConfigurationBuilders.Azure' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)"

**Comment by aitortxu** [comment]
Something similar has happened to me, 

just instaling Microsoft.Configuration.ConfigurationBuilders.Base and my project is failing with the same error.

**Comment by StephenMolloy** [comment]
The binaries inside the RTM nuget package did not get signed because of a missed step in the new build process we had to switch to between preview3 and rtm. I'm working out the kinks now, and 1.0.1 with signed binaries will be up later this afternoon.

**Comment by StephenMolloy** [comment]
#15

**Comment by ObadahFahmy** [comment]
I'm getting the same issue, in the sample web app it errors with "Could not load file or assembly 'Microsoft.Configuration.ConfigurationBuilders.Environment". The package version I am using (1.0.1) was published on the 25th of May 2018

**Comment by aitortxu** [comment]
Thank you @StephenMolloy, it's working fine now.

**Comment by ravitalveda** [comment]
In VS2017 You can enable an option as below:
Tools -> Options -> Projects and solutions -> Web Projects -> Check/Uncheck "Use the 64 bit version of IIS Express for websites and projects"

**Comment by CNBoland** [comment]
I'm using Microsoft.Configuration.ConfigurationBuilders.UserSecrets v1.0.2 as a Package Reference. I had to explicitly install Microsoft.Configuration.ConfigurationBuilders.Base v1.0.2 to avoid the assembly load error: 
_Could not load file or assembly 'Microsoft.Configuration.ConfigurationBuilders.Base, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'_
