### ISSUE TITLE
Error in Configuration Builder 'AzureKeyVault'::GetAllValues()

### ISSUE THREAD

**Issue by StephenMolloy** [aspnet/MicrosoftConfigurationBuilders#143]
See if we can repro this issue in the Azure SDK repo. It got closed because the customer took a different approach, not because the issue was solved.

https://github.com/Azure/azure-sdk-for-net/issues/15536

**Comment by kamalsivalingam** [comment]
@StephenMolloy We do see this error for .Net Framework Apps. Let me know what information do you need to replicate this issue. This randomly happens to one of the .Net Framework ASP.NET app every time the box is rebooted and has been a pain. We keep trying to recycle multiple times until the error goes away

**Comment by AndyMcKenna** [comment]
We were getting this when we first tried the AzureKeyVault ConfigurationBuilder on an Azure VM with a Managed Identity.  We had the AzureKeyVault::GetAllValues() null reference exception but further down there was a 403 Access Denied message.

The managed identity (application) didn't have Read and List permissions in the KeyVault's access policy

**Comment by SirElTomato** [comment]
@StephenMolloy I think I may have a similar issue. I have opened an issue [here](https://github.com/Azure/AppConfiguration/issues/462). Let me know if there is any extra info I can provide to help you.

**Comment by StephenMolloy** [comment]
I believe this is fixed by #134 and #163.

**Comment by xavierlaffargue** [comment]
Same issue here, I use Microsoft.Configuration.ConfigurationBuilders.Azure 2.0, how apply this fix?
