### ISSUE TITLE
Race condition in multithreading environment

### ISSUE THREAD

**Issue by ishatalkin** [aspnet/MicrosoftConfigurationBuilders#144]
Sometime Configuration Builders in multithreading environment become hanging at this place:
```
mscorlib_ni!System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib],[System.__Canon, mscorlib]].FindEntry(System.__Canon)+9e 
mscorlib_ni!System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib],[System.__Canon, mscorlib]].ContainsKey(System.__Canon)+b 
Microsoft.Configuration.ConfigurationBuilders.KeyValueConfigBuilder.GetValueInternal(System.String)+102 
```
According to [StackOverFlow](https://stackoverflow.com/a/33154222) this is due to race condition in thread unsafe dictionary. It's necessary to change type of KeyValueConfigBuilder._cachedValues from Dictionary to ConcurrentDictionary.

**Comment by StephenMolloy** [comment]
I suspect this is related to the race condition that is fixed in #134 and #167. Dictionary should be safe for multiple readers without heavy synchronization. Please reopen if this continues to repro after those fixes.
