### ISSUE TITLE
Getting error when starting app locally. Using .Net 4.8 ASP.Net

### ISSUE THREAD

**Issue by joshuamiller52** [aspnet/MicrosoftConfigurationBuilders#147]
![image](https://user-images.githubusercontent.com/18016442/101838344-0edae080-3b06-11eb-9ba9-1202f501c98f.png)
I keep getting this error and I can not figure out what URI would be invalid

![image](https://user-images.githubusercontent.com/18016442/101838642-9e808f00-3b06-11eb-8fdc-d85777678cb7.png)

I have full access to the Key vault I am trying to connect to and I have a connected service to my key vault setup in Visual studio for my project

**Comment by somy55** [comment]
Up

**Comment by Expecho** [comment]
Just to make sure, you keyvault is named `[VaultName]`? I suspect you need to remove []. You do need the name part. If your Vault Uri is `https://mykv.vault.azure.net/` the `vaultName` value in the web.config should be `mykv`

**Comment by StephenMolloy** [comment]
I believe @Expecho has the correct answer here. Closing the issue.
