### ISSUE TITLE
Unable to connect to KeyVault from Azure VM for WebForm .Net 4.8

### ISSUE THREAD

**Issue by blackeagle1111** [aspnet/MicrosoftConfigurationBuilders#150]
Hi all,
I have WebForm application need to move to Azure VM and I am having different time connecting to Azure KeyVault.
Managed Identity is on for that VM which currently hosts several applications (.NET, ASP.NET Core). They are able to connect to Key Vault.
This application works fine on my local environment due to Azure CLI and VS. However it failed on my Azure VM. 
I am really sure it has to do with versioning of the libraries. 
Does anyone have the same problems as described here? Please suggest thing to try.
Error:
![image](https://user-images.githubusercontent.com/3144869/105562096-c51d1280-5ccd-11eb-99a6-969de1228bd3.png)

Thanks in advance!

My current configuration:
web.config:
![image](https://user-images.githubusercontent.com/3144869/105562215-33fa6b80-5cce-11eb-841d-e7e50366a7d4.png)
web.dev.config
![image](https://user-images.githubusercontent.com/3144869/105562234-4bd1ef80-5cce-11eb-84d0-4c660faf69c2.png)
packages.config:
![image](https://user-images.githubusercontent.com/3144869/105562143-ebdb4900-5ccd-11eb-9bb5-98c9a3631c95.png)

**Comment by Expecho** [comment]
Can you try to see if the work around described in #139 solves the issue?

**Comment by blackeagle1111** [comment]
I have tried that and it still does not work.
Any other suggestions?

**Comment by blackeagle1111** [comment]
after adding ` <httpRuntime targetFramework="4.8" />` and it works

**Comment by blackeagle1111** [comment]
add  `<httpRuntime targetFramework="4.8" />` to web.config
