### ISSUE TITLE
configbuilders setup with windows containers

### ISSUE THREAD

**Issue by nreddipalle** [aspnet/MicrosoftConfigurationBuilders#151]
We are able to successfully use config builders and read config from Azure App Configuration. Currently, we are baking the keyfilter and azure app config endpoint URL into our image (as part of web.config)
labelFilter and endpoint are hardcoded before building the docker image.
`<add name="CS_AzureAppConfig" prefix="ConnStr_" stripPrefix="true" useAzureKeyVault="true" labelFilter="[sitecode]" type="Microsoft.Configuration.ConfigurationBuilders.AzureAppConfigurationBuilder, Microsoft.Configuration.ConfigurationBuilders.AzureAppConfiguration" endpoint="[Config_Store_Endpoint_Url]"/>`

To make our image a bit more generic, we are looking at ways to embed the labelFilter and endpoint during windows container runtime/pod startup.

tried to do this: https://github.com/aspnet/MicrosoftConfigurationBuilders#appsettings-parameters
by adding environment variable support 

```
<add name="Environment" type="Microsoft.Configuration.ConfigurationBuilders.EnvironmentConfigBuilder, Microsoft.Configuration.ConfigurationBuilders.Environment, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
<add name="CS_AzureAppConfig" prefix="ConnStr_" stripPrefix="true" useAzureKeyVault="true" labelFilter="${sitecode}" type="Microsoft.Configuration.ConfigurationBuilders.AzureAppConfigurationBuilder, Microsoft.Configuration.ConfigurationBuilders.AzureAppConfiguration" endpoint="${endpointURL}"/>

<appSettings configBuilders="Environment,CS_AzureAppConfig">
  <add key="endpointURL" value="qaendpointURL" />
  <add key="sitecode" value="testsite"
</appSettings>
```

so that while running the image, I want to pass labelFilter and azureappconfig endpoint as environment variables to the container but it is not working as expected.. 

Am i missing anything>> 

Not sure if this is causing any issue for me..

https://github.com/aspnet/MicrosoftConfigurationBuilders#environmentconfigbuilder

NOTE: In a Windows container environment, variables set at run time are only injected into the EntryPoint process environment. Applications that run as a service or a non-EntryPoint process will not pick up these variables unless they are otherwise injected through some mechanism in the container. For IIS/ASP.Net-based containers, the current version of ServiceMonitor.exe handles this in the DefaultAppPool only. Other Windows-based container variants may need to develop their own injection mechanism for non-EntryPoint processes.

Any help on this is appreciated.

**Comment by StephenMolloy** [comment]
You mention web.config, so I assume you're deploying an ASP.Net application. You don't mention what your base container image is though. I assume it's not derived from an ASP.Net or IIS container. **If you are based on one of these though, please re-open this issue so we can investigate further.**

As the note you found mentions, IIS and ASP.Net handle this with a tool called ServiceMonitor.exe which will inject environment variables into the w3wp service environment. You can look at the [IIS](https://github.com/microsoft/iis-docker/blob/main/windowsservercore-ltsc2019/Dockerfile) or [ASP.Net](https://github.com/microsoft/dotnet-framework-docker/blob/main/src/aspnet/4.8/windowsservercore-ltsc2019/Dockerfile) Dockerfiles to see how they accomplish this and replicate the approach in your container. Note that they use ServiceMonitor.exe as the EntryPoint. Without doing that, it wouldn't see the environment variables that are set.

**Comment by StephenMolloy** [comment]
[Windows Container FAQ](../docs/FAQ.md#windowscontainers)
