### ISSUE TITLE
Looking for secrets.json in debug path

### ISSUE THREAD

**Issue by LexRaaphorst** [aspnet/MicrosoftConfigurationBuilders#155]
One of our developers (not all) is having an issue with AddUserSecrets in a test project:

            var configuration = new ConfigurationBuilder()
                .AddUserSecrets<BaseTest>()
                .Build();

makes the fileprovider look for secrets.json in debug folder (net5.0) of the project. A MVC project in the same solution is looking in the correct folder for the secrets.json. Only difference I can find is VS2019 version (16.9.4 (not working) vs 16.9.3 (working)).

Any help is appreciated.

**Comment by StephenMolloy** [comment]
This repository contains Configuration *Builders* which support NetFx 4.7.1 and the old *.config file style configuration system. Your project is ASP.Net Core, and appears to be using the Configuration *Provider* from `https://www.nuget.org/packages/Microsoft.Extensions.Configuration.UserSecrets` which I believe is maintained in https://github.com/dotnet/runtime. I would direct this question there.
