### ISSUE TITLE
UserSecretsConfigBuilder support connectionStrings ?

### ISSUE THREAD

**Issue by xavierlaffargue** [aspnet/MicrosoftConfigurationBuilders#157]
I'm having trouble replacing ConnectionStrings with UserSecretsConfigBuilder.

Is it supported?
If not why ?
If so could have an example with a connectionString?

I've this error :
`Parser Error Message: The entry 'MyConnectionString' has already been added.`

Replacement works with my appSettings

Thank you

**Comment by StephenMolloy** [comment]
Yes, these builders should work with `<connectionStrings>`. Could you provide more details about your scenario to help in diagnosing the issue? What does your `<connectionStrings>` look like, and how is your config builder declared?

**Comment by StephenMolloy** [comment]
I'm going to close this issue for now. If you still have trouble with this, please post some repro config bits showing how you are using the builder so I can help you work it out.

The error is one from the .Net configuration system itself. It basically means that you've added a connection string with the name 'MyConnectionString' to the collection twice. I haven't checked how this works with V1, but `SectionHandler<ConnectionStringsSection>` should take care to not add duplicate entries. If you are able to get config builders to add duplicate entries here, I'd be happy to know about it.
