### ISSUE TITLE
Faking AzureAppConfigurationBuilder settings for pre-compilation

### ISSUE THREAD

**Issue by TimothyDJewell** [aspnet/MicrosoftConfigurationBuilders#158]
I'm not sure this is the right place to ask this question, since it is a bit convoluted, but the TL;DR is:
Is there an endpoint or credential we can provide to AzureAppConfigurationBuilder to get a fake/empty config?

Motivation/explanation of the need:
I'm currently working on adding pre-compilation to a .NET Framework application, but I've been running into issues because we recently added AzureAppConfigurationBuilder to our config file, which ends up looking something like:

```
<configBuilders>
	<builders>
		<add name="Environment" mode="Strict" type="Microsoft.Configuration.ConfigurationBuilders.EnvironmentConfigBuilder, Microsoft.Configuration.ConfigurationBuilders.Environment, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"/>
		<add name="AzureAppConfig" endpoint="${AzureAppConfigEndPoint}" useAzureKeyVault="true" type="Microsoft.Configuration.ConfigurationBuilders.AzureAppConfigurationBuilder, Microsoft.Configuration.ConfigurationBuilders.AzureAppConfiguration, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"/>
	</builders>
</configBuilders>
<appSettings configBuilders="Environment,AzureAppConfig">
	<add key="AzureAppConfigEndPoint" value=""/>
	<!-- ... -->
</appSettings>
```

The problem I seem to be running into is that aspnet_compiler.exe seems to result in evaluating `AppSettings.UseRandomizedStringHashAlgorithm`, which causes the full app config settings to need to load.  For pre-compilation, this seems unnecessary, since my build process shouldn't need to access my Azure config, which would only be configured for a deployed site.

Here's the stacktrace from calling:
```
C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\aspnet_compiler.exe -v \ -p **ProjectPath\obj\BuildConfiguration**\AspnetCompileMerge\Source -d **ProjectPath\obj\BuildConfiguration**\AspnetCompileMerge\TempBuildDir -errorstack
```

```
Microsoft (R) ASP.NET Compilation Tool version 4.8.4084.0
Utility to precompile an ASP.NET application
Copyright (C) Microsoft Corporation. All rights reserved.

**ProjectPath\obj\BuildConfiguration**\AspnetCompileMerge\Source\web.config(118): error ASPCONFIG: The configBuilder 'AzureAppConfig' failed while processing the configuration section 'appSettings'.: Error in Configuration Builder 'AzureAppConfig'::GetValue(**KeyName**)

[ArgumentException]: An endpoint URI or connection string must be provided for connecting to Azure App Configuration service via the 'endpoint' or 'connectionString' attribute.
   at Microsoft.Configuration.ConfigurationBuilders.AzureAppConfigurationBuilder.LazyInitialize(String name, NameValueCollection config)
   at Microsoft.Configuration.ConfigurationBuilders.KeyValueConfigBuilder.EnsureInitialized()
   at Microsoft.Configuration.ConfigurationBuilders.KeyValueConfigBuilder.GetValueInternal(String key)

[Exception]: Error in Configuration Builder 'AzureAppConfig'::GetValue(**KeyName**)
   at Microsoft.Configuration.ConfigurationBuilders.KeyValueConfigBuilder.GetValueInternal(String key)
   at Microsoft.Configuration.ConfigurationBuilders.KeyValueConfigBuilder.ProcessConfigurationSection(ConfigurationSection configSection)
   at System.Configuration.ConfigurationBuilderChain.ProcessConfigurationSection(ConfigurationSection configSection)

[ConfigurationErrorsException]: The configBuilder 'AzureAppConfig' failed while processing the configuration section 'appSettings'.: Error in Configuration Builder 'AzureAppConfig'::GetValue(**KeyName**) (**ProjectPath\obj\BuildConfiguration**\AspnetCompileMerge\Source\web.config line 118)
   at System.Configuration.BaseConfigurationRecord.EvaluateOne(String[] keys, SectionInput input, Boolean isTrusted, FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult)
   at System.Configuration.BaseConfigurationRecord.Evaluate(FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult, Boolean getLkg, Boolean getRuntimeObject, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Web.Util.AppSettings.GetAppSettingsSection()
   at System.Web.Util.AppSettings.EnsureSettingsLoaded()
   at System.Web.Util.StringUtil.GetNonRandomizedHashCode(String s, Boolean ignoreCase)
   at System.Web.Compilation.CompilationLock..cctor()
```

The current workaround I have is to remove "AzureAppConfig" from `appSettings/@configBuilders` prior to pre-compilation and then add it back after.
Another solution is to register my test environment's Azure config settings as environment variables during pre-compilation, but then my build is dependent on the test environments' config settings.  Ideally, I could register some sort of fake Azure config settings and avoid any dependency on my actual configuration.

**Comment by tafs7** [comment]
I have a similar, likely related, issue: trying to run a VSBuild task in Azure DevOps build pipeline, and my web.config uses the Azure KeyVault Config Builder.

If I don't turn off MVC View compilation (via the `MvcBuildViews` msbuild arg), it seems that the compiler will actually instantiate the entire configuration which will trigger the Azure Key Vault Config Builder to actually try to connect to the key vault, but at the point this msbuild task is running there's not an Azure connection context to use, so I get the following error:

```
##[error]ASPNETCOMPILER(0,0): Error ASPRUNTIME: Type is not resolved for member 'Azure.Identity.CredentialUnavailableException,Azure.Identity, Version=1.4.1.0, Culture=neutral, PublicKeyToken=92742159e12e44c8'.
```

I even tried to add 2 different tasks (Azure CLI and Azure Key Vault tasks) into the pipeline and give them both the ADO service connection, to see if having a previously authenticated azure context would "unclog" this by exposing that azure connection context to the MSBuild Task, and make it available to the `Azure.Identity.DefaultAzureCredential` that is being used by the Azure Key Vault ConfigBuilder......but no dice:

![image](https://user-images.githubusercontent.com/671795/135686799-4d96f69b-d42a-4318-a2bc-ed2b5faeeeda.png)

My current workaround is not ideal, as I am forced to give up compile-time error checking of my MVC views in production, and also take a bit of a performance penalty when loading views as they get compiled on demand.

Would love to know if there's a solution to this.  Thanks!

**Comment by StephenMolloy** [comment]
You might find that #173 in conjunction with the ability to draw builder settings from `<appSettings>` could help you avoid running unwanted config builders in various environments. Beyond that, setting up any fake storage to point builders to is beyond the scope of this project.
