### ISSUE TITLE
Custom AWS SSM Configuration Builder for .Net Framework 4.7.1

### ISSUE THREAD

**Issue by kolev9605** [aspnet/MicrosoftConfigurationBuilders#160]
So I've been trying to implement a custom `ConfigurationBuilder` that uses AWS SSM Parameter Store to store the keys.

No matter how I try to declare the builder in the web.config, I get the same error:

> Configuration Error Description: An error occurred during the
> processing of a configuration file required to service this request.
> Please review the specific error details below and modify your
> configuration file appropriately.
> 
> Parser Error Message: An error occurred loading a configuration file:
> Could not load file or assembly
> 'MyApp.Infrastructure.ConfigurationBuilders.AwsSsmConfigurationBuilder'
> or one of its dependencies. The system cannot find the file specified.
> 
> Source Error:
> 
> 
> Line 29:     <add name="MyAppLogsDbContext" connectionString="Data
> Source=.;Initial Catalog=MyAppLogs;Integrated
> Security=True;MultipleActiveResultSets=true;Max Pool Size=512;"
> providerName="System.Data.SqlClient" /> Line 30:  
> </connectionStrings> Line 31:   <appSettings
> configBuilders="ParameterStore"> Line 32:     <add key="MyAppSpaUrl"
> value="http://localhost:3000, https://localhost:3000" /> Line 33:    
> <add key="AllowedClientOrigin" value="*" />
> 
> Source File: D:\Apps\MyApp\MyAppweb\src\MyApp.Web\web.config    Line:
> 31
> 
> Assembly Load Trace: The following information can be helpful to
> determine why the assembly
> 'MyApp.Infrastructure.ConfigurationBuilders.AwsSsmConfigurationBuilder'
> could not be loaded.
> 
> 
> === Pre-bind state information === LOG: DisplayName = MyApp.Infrastructure.ConfigurationBuilders.AwsSsmConfigurationBuilder 
> (Partial) WRN: Partial binding information was supplied for an
> assembly: WRN: Assembly Name:
> MyApp.Infrastructure.ConfigurationBuilders.AwsSsmConfigurationBuilder
> | Domain ID: 2 WRN: A partial bind occurs when only part of the
> assembly display name is provided. WRN: This might result in the
> binder loading an incorrect assembly. WRN: It is recommended to
> provide a fully specified textual identity for the assembly, WRN: that
> consists of the simple name, version, culture, and public key token.
> WRN: See whitepaper http://go.microsoft.com/fwlink/?LinkId=109270 for
> more information and common solutions to this issue. LOG: Appbase =
> file:///D:/Apps/MyApp/MyAppweb/src/MyApp.Web/ LOG: Initial PrivatePath
> = D:\Apps\MyApp\MyAppweb\src\MyApp.Web\bin Calling assembly : (Unknown).
> === LOG: This bind starts in default load context. LOG: Using application configuration file:
> D:\Apps\MyApp\MyAppweb\src\MyApp.Web\web.config LOG: Using host
> configuration file:
> C:\Users\georgi.kolev\Documents\IISExpress\config\aspnet.config LOG:
> Using machine configuration file from
> C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
> LOG: Policy not being applied to reference at this time (private,
> custom, partial, or location-based assembly bind). LOG: Attempting
> download of new URL
> file:///C:/Users/georgi.kolev/AppData/Local/Temp/Temporary ASP.NET
> Files/vs/938f3e15/a8dabd2e/MyApp.Infrastructure.ConfigurationBuilders.AwsSsmConfigurationBuilder.DLL.
> LOG: Attempting download of new URL
> file:///C:/Users/georgi.kolev/AppData/Local/Temp/Temporary ASP.NET
> Files/vs/938f3e15/a8dabd2e/MyApp.Infrastructure.ConfigurationBuilders.AwsSsmConfigurationBuilder/MyApp.Infrastructure.ConfigurationBuilders.AwsSsmConfigurationBuilder.DLL.
> LOG: Attempting download of new URL
> file:///D:/Apps/MyApp/MyAppweb/src/MyApp.Web/bin/MyApp.Infrastructure.ConfigurationBuilders.AwsSsmConfigurationBuilder.DLL.
> LOG: Attempting download of new URL
> file:///D:/Apps/MyApp/MyAppweb/src/MyApp.Web/bin/MyApp.Infrastructure.ConfigurationBuilders.AwsSsmConfigurationBuilder/MyApp.Infrastructure.ConfigurationBuilders.AwsSsmConfigurationBuilder.DLL.
> LOG: Attempting download of new URL
> file:///C:/Users/georgi.kolev/AppData/Local/Temp/Temporary ASP.NET
> Files/vs/938f3e15/a8dabd2e/MyApp.Infrastructure.ConfigurationBuilders.AwsSsmConfigurationBuilder.EXE.
> LOG: Attempting download of new URL
> file:///C:/Users/georgi.kolev/AppData/Local/Temp/Temporary ASP.NET
> Files/vs/938f3e15/a8dabd2e/MyApp.Infrastructure.ConfigurationBuilders.AwsSsmConfigurationBuilder/MyApp.Infrastructure.ConfigurationBuilders.AwsSsmConfigurationBuilder.EXE.
> LOG: Attempting download of new URL
> file:///D:/Apps/MyApp/MyAppweb/src/MyApp.Web/bin/MyApp.Infrastructure.ConfigurationBuilders.AwsSsmConfigurationBuilder.EXE.
> LOG: Attempting download of new URL
> file:///D:/Apps/MyApp/MyAppweb/src/MyApp.Web/bin/MyApp.Infrastructure.ConfigurationBuilders.AwsSsmConfigurationBuilder/MyApp.Infrastructure.ConfigurationBuilders.AwsSsmConfigurationBuilder.EXE.

I've created a separate class library containing the `AwsSsmConfigurationBuilder` class. The namespace of the class is `Microsoft.Configuration.ConfigurationBuilders`. I've tried both `Microsoft.Configuration.ConfigurationBuilders` and the original namespace of the file - same error.

This is the code of the `AwsSsmConfigurationBuilder` builder. I inherit form `KeyValueConfigBuilder` class:

```
    public class AwsSsmConfigurationBuilder : KeyValueConfigBuilder
        {
            private string BaseParameterPath = "/myApp/apiKeys";
            private static IAmazonSimpleSystemsManagement _client;
    
            public AwsSsmConfigurationBuilder()
            {
                _client = new AmazonSimpleSystemsManagementClient();
            }
    
            public override void Initialize(string name, NameValueCollection config)
            {
                base.Initialize(name, config);
    
                if (config["ssmPrefix"] == null)
                {
                    return;
                }
    
                BaseParameterPath = config["ssmPrefix"];
            }
    
            public override ICollection<KeyValuePair<string, string>> GetAllValues(string prefix)
            {
                if (_client == null)
                {
                    return null;
                }
    
                var request = new GetParametersByPathRequest
                {
                    Path = $"{BaseParameterPath}/{prefix}",
                    WithDecryption = true,
                };
    
                var response = _client.GetParametersByPathAsync(request).Result;
    
                var result = response.Parameters.ToDictionary(param => param.Name, param => param.Value, StringComparer.OrdinalIgnoreCase);
    
                return result;
            }
    
            public override string GetValue(string key)
            {
                if (_client == null)
                    return null;
    
                var request = new GetParameterRequest
                {
                    Name = $"{BaseParameterPath}/{key}",
                    WithDecryption = true,
                };
    
                var response = _client.GetParameterAsync(request).Result;
    
                return response.Parameter.Value;
            }
        }
```

This is the structure currently of the `web.config`:
```
    <configuration>
      <configSections>
    	...
        <section name="configBuilders" 
                 type="System.Configuration.ConfigurationBuildersSection, System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" 
                 restartOnExternalChanges="false" 
                 requirePermission="false" />
      </configSections>
      <configBuilders>
        <builders>
          <add name="ParameterStore" type="Microsoft.Configuration.ConfigurationBuilders, AwsSsmConfigurationBuilder" />
        </builders>
      </configBuilders>
    
      <appSettings configBuilders="ParameterStore">
        <add key="TestConfig" value="From the web app" />
    	...
      </appSettings>
      ...
    </configuration>
```

As the error says, the Web project can't load the assembly, but there are no clear answers why. I've tried multiple combinations in the `type` attribute - specifying the full path for my custom builder, including the namespace - nothing worked - same error every time. I was referring to this repo https://github.com/Kirkaiya/AwsSsmConfigBuilderPoC since that is the only solution to solving my issue, but it didn't work.

Am I missing something?

Thank you in advance!

**Comment by ArcaneTSGK** [comment]
@kolev9605 Try changing the namespace of your custom builder in your project, and place it in a folder such as MyProject/Infrastructure then do

```
<add name="ParameterStore" type="MyProject.Infrastructure.AwsSsmConfigurationBuilder, MyProject" />
```

**Comment by kolev9605** [comment]
@ArcaneTSGK Thank you, it stopped throwing the previous error using this:
`<add name="ParameterStore" mode="Greedy" type="MyApp.Infrastructure.ConfigurationBuilders.AwsSsmConfigurationBuilder, MyApp.Infrastructure.ConfigurationBuilders" />`

Although now I am facing a new error that has very little detail in it. Have you seen anything similar?

`Server Error in '/' Application.
Configuration Error
Description: An error occurred during the processing of a configuration file required to service this request. Please review the specific error details below and modify your configuration file appropriately.

Parser Error Message: An error occurred loading a configuration file: Exception has been thrown by the target of an invocation.

Source Error:


...
Line 33:   <appSettings configBuilders="ParameterStore">
...

Source File: D:\Apps\MyApp\web\src\MyApp.Web\web.config    Line: 33
`

**Comment by ArcaneTSGK** [comment]
> @ArcaneTSGK Thank you, it stopped throwing the previous error using this:
> `<add name="ParameterStore" mode="Greedy" type="MyApp.Infrastructure.ConfigurationBuilders.AwsSsmConfigurationBuilder, MyApp.Infrastructure.ConfigurationBuilders" />`
> 
> Although now I am facing a new error that has very little detail in it. Have you seen anything similar?
> 
> ```
> Server Error in '/' Application.
> Configuration Error
> Description: An error occurred during the processing of a configuration file required to service this request. Please review the specific error details below and modify your configuration file appropriately.
> 
> Parser Error Message: An error occurred loading a configuration file: Exception has been thrown by the target of an invocation.
> 
> Source Error:
> 
> 
> ...
> Line 33:   <appSettings configBuilders="ParameterStore">
> ...
> 
> Source File: D:\Apps\MyApp\web\src\MyApp.Web\web.config    Line: 33
> ```

This is caused by the application being unable to locate the configuration builder specified, check your naming/namespaces are correct

For example if you have the following file structure

MyApp/Infrastructure/ConfigurationBuilders please check that at the top of your AwsSsmConfigurationBuilder it has the relevant namespace

```
namespace MyApp.Infrastructure.ConfigurationBuilders
{
    public class AwsSsmConfigurationBuilder : KeyValueConfigBuilder
    {
       //...
    }
}
```

**Comment by kolev9605** [comment]
Unfortunately, I don't think that's the issue because I can see in the debugger that it clearly finds the assembly.

**Comment by StephenMolloy** [comment]
Your first error looks like a simple binding failure. I don't know the details of your project, but make sure your config builder is built before your web project, and make sure your web project is correctly pulling in your config builder assembly *as well as Micorosoft.Configuration.ConfigurationBuilders.Base.dll*. They should both be in your web project's 'bin' directory. After that, just be sure you've got the correct Class and Assembly names referenced when you declare your config builder in the `<configBuilders>` section. There are mismatches in the snips you posted above... though I assume that's simply a product of trying to debug through all this while filing this issue.

**Comment by StephenMolloy** [comment]
I presume this has been worked out. It does not appear to be a particular issue stemming from the packages from this repo anyway.
