### ISSUE TITLE
If preload is disabled, KeyVaultConfigBuilder throws an ArgumentNullException

### ISSUE THREAD

**Issue by heaths** [aspnet/MicrosoftConfigurationBuilders#161]
https://github.com/aspnet/MicrosoftConfigurationBuilders/blob/22371104020c6540446f86f5102990ac7ed8f02c/src/Azure/AzureKeyVaultConfigBuilder.cs#L102-L105

If `_preload` is `false`, then `_allKeys` is null and https://github.com/aspnet/MicrosoftConfigurationBuilders/blob/22371104020c6540446f86f5102990ac7ed8f02c/src/Azure/AzureKeyVaultConfigBuilder.cs#L132 ends up throwing an `ArgumentNullException` citing the `source` parameter for `Enumerable.Contains`.

**Comment by heaths** [comment]
FWIW, preloading secrets from Key Vault - especially when your Key Vault has many secrets (1 per app is recommended) - can lead to rate throttling, especially in clustered apps starting up all at once.

Instead, the Key Vault team recommends [using AppConfig with a link to Key Vault](https://docs.microsoft.com/samples/azure/azure-sdk-for-net/app-secrets-configuration/) for general configuration needs, where AppConfig can have links to secrets that [Microsoft.Extensions.Configuration.AzureAppConfiguration](https://nuget.org/packages/Microsoft.Extensions.Configuration.AzureAppConfiguration) can resolve by default, though it's not hard to achieve from any configuration builder.

**Comment by karshinlin** [comment]
+1 on this issue. More details from customer reported incidents: 
- the preload setting is default True for the AzureKeyVaultConfigurationBuilder. We've seen this ArgumentNullException from _allKeys being null when this builder is used for the <connectionStrings> section (not sure if this is a red herring). 
- possible theory is a race condition in the initialization logic, where the _lazyInitialized flag is set before the secrets are actually preloaded from Key Vault:
https://github.com/aspnet/MicrosoftConfigurationBuilders/blob/22371104020c6540446f86f5102990ac7ed8f02c/src/Base/KeyValueConfigBuilder.cs#L283-L295
Initialized here: 
https://github.com/aspnet/MicrosoftConfigurationBuilders/blob/22371104020c6540446f86f5102990ac7ed8f02c/src/Base/KeyValueConfigBuilder.cs#L138
But preload logic is farther down in the initialization logic:
https://github.com/aspnet/MicrosoftConfigurationBuilders/blob/22371104020c6540446f86f5102990ac7ed8f02c/src/Azure/AzureKeyVaultConfigBuilder.cs#L102-L105

**Comment by StephenMolloy** [comment]
Fixed by #163. Well, and also by #134 which hopefully avoids any race in the first place. But I think a Lazy<T> approach in #163 is also an upgrade in this scenario.
