### ISSUE TITLE
enabled option doesn't seem to be honored

### ISSUE THREAD

**Issue by johnayoub** [aspnet/MicrosoftConfigurationBuilders#185]
I currently have the following builder in web.config but toggling the value of enabled to disabled/false still executes the builder

```xml
			<add name="KeyVault"
				 enabled="disabled"
				 vaultName="${KeyVaultName}"
				 mode="Greedy"
				 type="Microsoft.Configuration.ConfigurationBuilders.AzureKeyVaultConfigBuilder, Microsoft.Configuration.ConfigurationBuilders.Azure" />
```

**Comment by StephenMolloy** [comment]
The 'enabled' feature isn't documented and hasn't been released yet. It only got checked in in the last month. I'm trying to clean and update the repo in my spare moments since we haven't refreshed in quite some time. It's slow progress since it tends to draw lower priority than the other things on my plate.

**Comment by rdillion** [comment]
When I go to the docs from the repo home they talk about the enabled attribute so it is very confusing when it does not work. I've wasted some time trying to get this to work before seeing this issue.

Usually the docs line up with the currently released version.

**Comment by StephenMolloy** [comment]
Sorry about that. I've been pulled in 17 different directions over the last year and as you've noticed, this repo didn't get pushed to release yet. It was not the expectation for this to get delayed so long. We've got a team running through tests on this current repo now and anticipate that a release should finally be available this month.

I don't anticipate that there will be much activity in this repo going forward, as ASP.Net Core is where most current development resources are allocated in the MS web space. But if there is need to do a refresh of these builders in the future, I'll try to do a better job of keeping a development branch off of main so the front-page docs aren't mismatched with the current release.
