### ISSUE TITLE
Plans for a release in the near future?

### ISSUE THREAD

**Issue by henrikrxn** [aspnet/MicrosoftConfigurationBuilders#187]
Hi

Thank for the work on this.

This problem is also bothering us greatly 
https://github.com/aspnet/MicrosoftConfigurationBuilders/issues/140

Are there any plans for a release in the near future including all the fixes done since last release ?

**Comment by gpetrounrt** [comment]
@StephenMolloy is there a feed that we could use to get the latest package? Otherwise, perhaps you could upload a preview package in NuGet?

**Comment by StephenMolloy** [comment]
3.0 preview1 is out now. There is no specific timeline for removing the preview tag, but I don't have any planned work to add other than responding to feedback that comes back on the preview.

**Comment by henrikrxn** [comment]
Tested 3.0.0-preview1 and it seems to have resolved the issues we saw primarily with concurrency / race-conditions.

**Comment by henrikrxn** [comment]
@StephenMolloy Anything in the way of releasing 3.0.0?
