### ISSUE TITLE
KeyValueConfigException is internal

### ISSUE THREAD

**Issue by philipwolfe** [aspnet/MicrosoftConfigurationBuilders#195]
If KeyValueConfigException is internal, so no subclasses can catch this exception to handle it when it is thrown from KeyValueConfigBuilder.  And I also think no 'hosting' code can catch this exception.   Is this intentional to let internal exceptions to leak out of the library?

**Comment by philipwolfe** [comment]
@StephenMolloy or @terrajobst Can you comment on this before releasing V3?

**Comment by StephenMolloy** [comment]
Addressed by #204.
