### ISSUE TITLE
KeyValueConfigBuilders are broken when upgrading

### ISSUE THREAD

**Issue by philipwolfe** [aspnet/MicrosoftConfigurationBuilders#196]
Here is a sample project that runs with the current version.  It is a simple example using the Json file config builder but this problem is with all new config builders.  

https://github.com/philipwolfe/ConfigBuildersTester

When you upgrade the project to 3.0 and change the 'Expand' value to 'Token', the exception is thrown about not finding an ISectionHandler.  (Which I have reported previously as a problem.)  This will prevent us from upgrading.

We are moving away from using appSettings and connectionStrings because of traceability.  When you have a project that references 20 other libraries that all have their own config settings, it is not practical to tell which settings belong to which library.  When settings are shared, one does not know when to remove a setting, so no one cleans up settings.  With applicationSettings sections, each library declares what settings it needs and "is noisy" about it when they are missing.  We are hoping this can get resolved before release.  Thanks.

**Comment by philipwolfe** [comment]
@StephenMolloy or @terrajobst Can you comment on this before releasing V3?

**Comment by StephenMolloy** [comment]
One more thing. If your real-case scenario can't leverage Token/SectionHandler's, then you could always try to bring back the old `Expand` behavior with your own derived KVConfigBuilder, or something like this [this wrapper approach](https://github.com/aspnet/MicrosoftConfigurationBuilders/tree/main/samples/SamplesLib/ExpandWrapper.cs) as is demonstrated in the [SampleConsoleApp](https://github.com/aspnet/MicrosoftConfigurationBuilders/tree/main/samples/SampleConsoleApp/App.config#L36-L39).
