### ISSUE TITLE
Need ability to override AzureKeyVaultConfigBuilder GetCredential()

### ISSUE THREAD

**Issue by jordanbean-msft** [aspnet/MicrosoftConfigurationBuilders#199]
I can see that the latest version of the AzureKeyVaultConfigBuilder.cs file has the ability to allow derived classes to override the GetCredential() method. Please publish a new stable release of the NuGet package for this library so implementors can override the GetCredential() method.

**Comment by StephenMolloy** [comment]
Sorry for the long delay here. This OOB project often get's buried at the bottom of my priority list.

Soon. We're currently doing internal verification of release packages. Shouldn't be much wait now. The 'preview1' package has proven to be pretty stable though if you just can't wait.
