### ISSUE TITLE
Expose SecretClientOptions to be set by a derived class in AzureKeyVaultConfigBuilder

### ISSUE THREAD

**Issue by benvanderlinde** [aspnet/MicrosoftConfigurationBuilders#201]
We have a specific scenario where we would like to use the AKV config builder, but we are operating behind a proxy server.

The rules for which http calls need to traverse a proxy vs calls that do not, are complex and difficult to capture using a 'proxy bypass list' configured in the web.config, so it's preferable to make these decisions in app code.

Exposing the SecretCllientOptions in-conjunction with the TokenCredential (via GetCredential(0)), allows the pipeline transport to be configured to use a proxy.

**Comment by StephenMolloy** [comment]
#207
