### ISSUE TITLE
AzureAppConfigurationBuilder uses hardcoded DefaultAzureCredential() to read Key Vault but should use existing GetCredential()

### ISSUE THREAD

**Issue by Juraj2** [aspnet/MicrosoftConfigurationBuilders#230]
### AzureAppConfigurationBuilder uses hardcoded DefaultAzureCredential() to read Key Vault but should use existing GetCredential()
[AzureAppConfigurationBuilder.cs](https://github.com/aspnet/MicrosoftConfigurationBuilders/blob/ea50da297ce168877f5121b8a1409b89698e2690/src/AzureAppConfig/AzureAppConfigurationBuilder.cs) always uses DefaultAzureCredential() when reading App Configuration `Key-value references` to `Key Vault`. It should use already existing virtual method [GetCredential()](https://github.com/aspnet/MicrosoftConfigurationBuilders/blob/ea50da297ce168877f5121b8a1409b89698e2690/src/AzureAppConfig/AzureAppConfigurationBuilder.cs#L227) instead.

### Functional impact
Classes that inherit from `AzureAppConfigurationBuilder` and override the `protected virtual TokenCredential GetCredential()` still cannot influence which `TokenCredential` is used when reading App Configuration values that are referencing `Key Vault`.

### Expected result
When classes that inherit from `AzureAppConfigurationBuilder` override the `protected virtual TokenCredential GetCredential()` then the `GetCredential()` should also be used for App Configuration `Key-value references` to `Key Vault`

### Actual result
When classes that inherit from `AzureAppConfigurationBuilder` override the `protected virtual TokenCredential GetCredential()` then the `GetCredential()` is only used to read `Key-values` from App Configuration. But when reading App Configuration `Key-value references` that reference `Key Vault` then always the hardcoded `new DefaultAzureCredential()` is used. 

### Further technical details
There is a bug in the code in [AzureAppConfigurationBuilder.cs](https://github.com/aspnet/MicrosoftConfigurationBuilders/blob/ea50da297ce168877f5121b8a1409b89698e2690/src/AzureAppConfig/AzureAppConfigurationBuilder.cs) in [private SecretClient GetSecretClient()](https://github.com/aspnet/MicrosoftConfigurationBuilders/blob/ea50da297ce168877f5121b8a1409b89698e2690/src/AzureAppConfig/AzureAppConfigurationBuilder.cs#L387) method. It should use already existing virtual method [GetCredential()](https://github.com/aspnet/MicrosoftConfigurationBuilders/blob/ea50da297ce168877f5121b8a1409b89698e2690/src/AzureAppConfig/AzureAppConfigurationBuilder.cs#L227) instead of hardcoded `new DefaultAzureCredential()`- the same way as it is used in  [AzureKeyVaultConfigBuilder.cs](https://github.com/aspnet/MicrosoftConfigurationBuilders/blob/ea50da297ce168877f5121b8a1409b89698e2690/src/Azure/AzureKeyVaultConfigBuilder.cs)

**Comment by skwazza09** [comment]
Facing the same issue with AzureAppConfigurationBuilder. Able to load the AppConfig values just fine, however when reading App Configuration Key-value references that reference Key Vault it always uses the default credential.

**Comment by masonhuemmer** [comment]
Any update?

**Comment by Juraj2** [comment]
I impelemted the fix for it. I am waiting for the pull request approval so it gets to the next release.
