### ISSUE TITLE
Support for App Configuration Snapshots

### ISSUE THREAD

**Issue by masonhuemmer** [aspnet/MicrosoftConfigurationBuilders#234]
Here are two docs that explain what snapshots are and how to implement. 

https://learn.microsoft.com/en-us/azure/azure-app-configuration/concept-snapshots

https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-create-snapshots?WT.mc_id=Portal-Microsoft_Azure_AzConfig&tabs=dotnet

**Comment by StephenMolloy** [comment]
Added in #249
