### ISSUE TITLE
feat: EnvironmentConfigBuilder mode=Token default value support

### ISSUE THREAD

**Issue by jeacott1** [aspnet/MicrosoftConfigurationBuilders#240]
It would be very helpful if the EnvironmentConfigBuilder Token mode supported configuration of default values in a similar way to the standard java construct ${SOME_ENV_VAR: defaultValue}  (note the value after the colon)

This would allow non breaking usage of tokens in existing configurations and ease gradual migration as this pattern also more closely mimics the mechanism in .net 5+ where the json content already behaves as default config without requiring templating or other intrusive mechanisms.

**Comment by StephenMolloy** [comment]
I was going to suggest that this - while a nice idea - could run into several complications when deciding what character would be a valid delimiter between the key name and the default value. For and environment variable config builder, ':' feels easy. Would the same be true of a JSON config builder? What about a '/' character - which iirc is actually used as a 'version' specifier for key vault keys. How would we handle the situation where the newer advanced [ConnectionStringsSectionHandler2](../blob/main/docs/SectionHandlers.md#connectionstringssectionhandler2) is in use, as it also ascribes special meaning to the ':' delimiter - or at least looks for a ':' as part of it's well-known suffixes it's looking for.

And I was also going to suggest that for your own purposes, it wouldn't be hard to extend the `EnvironmentConfigBuilder` like so:
```cs
    public class EnvironmentWithDefault : EnvironmentConfigBuilder
    {
        public override void Initialize(string name, NameValueCollection config)
        {
            base.Initialize(name, config);

            // Allow ':' as a way to specify default values in 'Token' mode.
            if (Mode == KeyValueMode.Token)
            {
                CharacterMap.Remove(":");
                TokenPattern = @"\$\{(\w[^}]*)\}";    // Need to be more lenient for default values.
            }
        }

        public override string GetValue(string key)
        {
            if (Mode != KeyValueMode.Token)
                return base.GetValue(key);

            var parts = key.Split(new[] { ':' }, 2);
            return base.GetValue(parts[0]) ?? (parts.Length > 1 ? parts[1] : null);
        }
    }
```

Making this change in the base package (or even just the Environment package) for everybody could be destabilizing for folks who are doing their own thing and just wanted to click the upgrade button on their nuget list. And navigating the world of possibilities with regards to which character is safe and how to even parse a default value when we give people the opportunity to bring their own token format... it's all kind of a nightmare. But the clue is actually in that last bit.

_We give people the opportunity to bring their own token format_ - via the `tokenPattern` attribute.

With #247, I've leveraged that ability to check for a second capture in the token match which we can use as the default value. That way, users retain full flexibility over the format of how they want or need to specify tokens and defaults. Just update the `tokenPattern` attribute so it potentially captures a second value to use as a default.

I've decided not to opt-in to a new default-capturing pattern for all the rambling fears above. But all you would need to do to get this 'default value support' on your environment config builder as you described in your post would be to change the `tokenPattern` like so:

```xml
  <configBuilders>
    <builders>
      <add name="DefaultEnv" mode="Token" tokenPattern="\$\{(\w[\w-_$@#+,.~]*)(?:\:([^}]*))?\}" type="Microsoft.Configuration.ConfigurationBuilders.EnvironmentConfigBuilder, Microsoft.Configuration.ConfigurationBuilders.Environment" />
    </builders>
  </configBuilders>

  <appSettings configBuilders="DefaultEnv">
    <add key="TestingEnvDefaults1" value="${WINDIR:Should not see default.}" />
    <add key="TestingEnvDefaults2" value="${ENV_VAR_DOES_NOT_EXIST:But a default value is here.}" />
    <add key="TestingEnvDefaults3" value="${EMPTY_DEFAULT_VALUE:}" />
    <add key="TestingEnvDefaults-DefaultValueNotRequiredWithThisPattern" value="${OS}" />
  </appSettings>
```

I've updated the [SampleConsoleApp](../blob/main/samples/SampleConsoleApp/App.config) and the [general documentation](../blob/main/docs/KeyValueConfigBuilders.md) to demonstrate.
