### ISSUE TITLE
Allow keyvault name configuration value to be specified via environment variable

### ISSUE THREAD

**Issue by Philo** [aspnet/MicrosoftConfigurationBuilders#27]
Having to specify the name of the key vault to use within the builder configuration section of the `web.config` significantly limited the usefulness of this builder as a way to store sensitive configuration information for multiple environments. 

The current approach requires that build/release artifacts need to be specifically packaged for different key vaults (test, qa, pre-prod, prod) instead of being able to deploy the same artifacts and use runtime configuration to determine which key vault should be used.

I would propose that it should be possible to configure the `vaultName` or `vaultUri` settings via environment variables such as `KEYVAULT_NAME` or `KEYVAULT_ENDPOINT`.

Is this something that the maintainers of this project would consider, if so it would be a good feature for a PR?

**Comment by rahulpnath** [comment]
Prefer having this as part of the configuration value if possible and have the config builder be able to read the value of that key. But it kind of goes into a cyclic loop of a config builder looking into the config itself :)

**Comment by arjntc1** [comment]
Philo, it sounds like you have specific business need that you may be able to use with a custom configBuilder, but I agree with rahulpnath on this one.  You do not want that in the default configBuilders.  You could ultimately have a spidering effect ("think of a goto in code") going from configBuilder to configBuilder.  It's better to keep them basic -- giving you the power to create a derived class to handle it for your specific needs. HTH

**Comment by henrybeen** [comment]
I would agree with @Philo that it would be great if we could vary the VaultName (and/or Uri) in the configuration of the KeyVaultConfigurationBuilder. I believe it is not a specific business need, but actually quitte common to use different KeyVaults for different environments (like testing, production, ..)

Would you accept an Pull Request for fixing this by allowing the VaultName to be specified as an AppSetting? For example with syntax like one of the options below? I would prefer option three over two and two over one.

<add name="Secrets"
           type="Microsoft.Configuration.ConfigurationBuilders.AzureKeyVaultConfigBuilder, Microsoft.Configuration.ConfigurationBuilders.Azure, Version=1.0.0.0, Culture=neutral"
           vaultName="{AppSettingName}"
           connectionString="RunAs=App" />

<add name="Secrets"
           type="Microsoft.Configuration.ConfigurationBuilders.AzureKeyVaultConfigBuilder, Microsoft.Configuration.ConfigurationBuilders.Azure, Version=1.0.0.0, Culture=neutral"
           vaultName="AppSettingName"
           vaultNameIsAppSetting="true
           connectionString="RunAs=App" />

<add name="Secrets"
           type="Microsoft.Configuration.ConfigurationBuilders.AzureKeyVaultConfigBuilder, Microsoft.Configuration.ConfigurationBuilders.Azure, Version=1.0.0.0, Culture=neutral"
           vaultNameFromAppSetting="AppSettingName"
           connectionString="RunAs=App" />

**Comment by Philo** [comment]
Good to see that I'm not the only person would like some addition options around the configuration of this , perhaps the maintainer's could re-evaluate there thoughts on this and we can find a good solution that all would be happy with.

**Comment by janiilmari** [comment]
Upon further testing we found out that #36 doesn't solve the problem for us. We deploy to Azure Web App and would like to have the key vault name defined in the Web App's AppSettings. Those AppSettings are not populated to web.config's AppSettings and configBuilder cannot find the key vault name.

We'll try to to circumvent this by doing some web.config transformations during release (as described here: https://blogs.msdn.microsoft.com/ericparvin/2018/03/19/manage-web-config-values-between-environments-in-release-management-and-tfs/).

**Comment by henrybeen** [comment]
@janiilmari I have a working example here if you're interested: https://github.com/henrybeen/secrets-configbuilders/tree/master/src

Just wondering, have you also tried specifying the keyVault name from Azure DevOps (ex-VSTS), using the Web App release task?

**Comment by StephenMolloy** [comment]
V2.0 is in the works, and we've got a plan to address this. Most parameters for the config builders in this suite can be grabbed from appSettings now, using the same ${settingName} syntax that is used for 'expand' mode in other config sections. The only catch is that if your config builder is being applied to appSettings, this mechanism will not work in expand mode. Also, settings added by builders later in the chain won't be available either obviously. Check out #42 to see if this works for your needs.

**Comment by StephenMolloy** [comment]
Hit the 'comment' button before adding to that previous bit which I copy/pasted from #38.

By enabling the ability to draw config builder parameters like 'vaultName' from appSettings, you can indirectly get the value from anywhere you like. If you want to get it from the environment, then add the environment config builder to your appSettings section so the vault name will be there for your key vault builder to consume.

**Comment by StephenMolloy** [comment]
v2.0 beta packages will be out on nuget later tonight.
