### ISSUE TITLE
Apply to more than AppSettings and ConnectionStrings

### ISSUE THREAD

**Issue by StephenMolloy** [aspnet/MicrosoftConfigurationBuilders#33]
Hey all. When we first imagined these Key/Value config builders and how they could be useful for securing secrets or assisting lift and shift into container environments, the obvious targets for injecting config values were the two most prominent key/value config sections. AppSettings and ConnectionStrings. The configuration builders feature in the framework is not restricted to those two sections though. When considering improvements to be made in vNext of these Key/Value-centric config builders, I wondered if anyone wants to use these on config sections other than the two mentioned above. So... some questions:

1. Would you want to be able to apply values from a key/value _source_ to a config section other than the two that are already handled? If so, which sections? And is 'Expand' mode sufficient for your needs, or are 'Strict' or 'Greedy' preferrable in some cases?
2. If the key/value base code were changed to operate on any config section using an enumerable-ish config section handler*, what would be the preferred way to find these handlers for other sections? (Keep in mind, the config system is initialized and some sections are loaded before any 'startup' code gets to run.) Reflection magic? Application of a 'dummy' builder to the config section that registers the handler for that section for builders later in the list?

*-A handler could expose the config section it handles as an enumeration of key/config-unit pairs, and also contain a Insert/ReplaceValue(config-unit, key, value) method that knows how to insert the looked-up config value for the given key into the config-unit returned by its own enumeration.

**Comment by MarceloRamos1** [comment]
Hello,

 I've been looking into a way to implementing something similar on other sections like sqlCacheDependency. Currently I've been injecting these values through reflection.

Indeed being able to inject these settings on the fly via something like configBuilder is a great approach.. If there is currently a way of doing this other than the two sections above, I would appreciate if you could share, as I was unable to get this working so far.

**Comment by cyciopes** [comment]
I'd like apply it to WCF client endpoint. And for me, Expand mode is fine. Thank you.
```
 <system.serviceModel configBuilders="SimpleJson">
  <bindings>
   <basicHttpBinding>
    <binding name="UserPortBinding" />
   </basicHttpBinding>
  </bindings>
  <client>
   <endpoint address="${jsonSetting1}"
    binding="basicHttpBinding" bindingConfiguration="UserPortBinding"
    contract="UserService.User" name="UserPort" />
  </client>
 </system.serviceModel>
```

**Comment by cyciopes** [comment]
Hi @MarceloRamos1 , would you please share some sample code about your reflection approach? Thanks.

**Comment by StephenMolloy** [comment]
#42 addresses this with the introduction of [section handlers](https://github.com/aspnet/MicrosoftConfigurationBuilders#sectionhandlers). A 2.0 beta package should be available on nuget later tonight.
