### ISSUE TITLE
Regression: Incorrect ConfigurationBuilders.Base dependency / package signing

### ISSUE THREAD

**Issue by seangwright** [aspnet/MicrosoftConfigurationBuilders#34]
The ConfigurationBuilder implementations (`ConfigurationBuilders.UserSecrets` still have a dependency range for `ConfigurationBuilders.Base` of >= `1.0.0`.

When I install `v1.0.2` of `ConfigurationBuilders.UserSecrets` it pulls in `v1.0.0` of `ConfigurationBuilders.Base` which causes issues in Web Forms `.ascx`/`.aspx` files for CodeDom compilation.

After digging through the errors, which are not well surfaced, I find that it's due to `ConfigurationBuilders.Base` `v1.0.0` not being signed correctly.

When I install `ConfigurationBuilders.Base` `v1.0.2` the problem is fixed.

Can the `ConfigurationBuilders.Base` dependency range for all ConfigurationBuilder implementation packages be changed to >= `1.0.2` so I don't have to explicitly install `ConfigurationBuilders.Base`?

--Edit

Some additional details

My project has `Microsoft.Configuration.ConfigurationBuilders.UserSecrets` `v1.0.2` installed but not an explicit package reference to `Microsoft.Configuration.ConfigurationBuilders.Base`

When I build my project and check the binary version of `Microsoft.Configuration.ConfigurationBuilders.Base` in my `\bin` I'm getting `v1.0.0`.

```
$ sigcheck App/bin/Microsoft.Configuration.ConfigurationBuilders.Base.dll

Sigcheck v2.20 - File version and signature viewer
Copyright (C) 2004-2015 Mark Russinovich
Sysinternals - www.sysinternals.com

C:\path\to\App\bin\Microsoft.Configuration.ConfigurationBuilders.Base.dll:
        Verified:       Unsigned
        Link date:      6:32 PM 5/21/2018
        Publisher:      Microsoft
        Description:    Basic
        Product:        Basic
        Prod version:   1.0.0.0
        File version:   1.0.0.0
        MachineType:    32-bit
```

This version has the signing problems and my Web Forms `.ascx`/`.aspx` files stop getting intellisense and I see this error in my VS Error List which is very unhelpful in diagnosing the problem.

`Severity	Code	Description	Project	Path	File	Line	Suppression State
Warning		C:\path\to\control\LogonForm.ascx: ASP.NET runtime error: The type initializer for 'System.Web.Compilation.CompilationLock' threw an exception.	App C:\path\to\control	C:\path\to\control\LogonForm.ascx	1	
`

I then look in my packages (I'm using `PackageReference`) `C:\Users\SeanGWright\.nuget\packages\microsoft.configuration.configurationbuilders.base` and see `1.0.0` even though I previously deleted it - so Nuget is resolving the oldest valid version of `Microsoft.Configuration.ConfigurationBuilders.Base`.

As soon as I explicitly install `v1.0.2` of`Microsoft.Configuration.ConfigurationBuilders.Base` everything works fine.

When I had `Microsoft.Configuration.ConfigurationBuilders.UserSecrets` `v1.0.1` everything worked fine because `v1.0.1` had an dependency range for `Microsoft.Configuration.ConfigurationBuilders.Base` of >= `1.0.1`

**Comment by seangwright** [comment]
@StephenMolloy Any possibility we could get a package release to correct this?

**Comment by StephenMolloy** [comment]
v2.0 beta preview should get pushed out today and address this issue.

The intent was to not require a minor update in the individual config builder packages to necessitate an upgrade to the base package... but that's not really how this worked out. Version dependency will be more strict in 2.0.
