### ISSUE TITLE
AzureKeyVaultConfigBuilder - Allow to specify vaultName in appSettings

### ISSUE THREAD

**Issue by martinoss** [aspnet/MicrosoftConfigurationBuilders#38]
I would like to make use of the variable substitution in my release pipeline, but I'm not able to replace the vaultName with this mechanism (https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/transforms-variable-substitution?view=vsts#xmlvarsubs)

It would be very helpful if I can specify the vaultName in appSettings.

**Comment by StephenMolloy** [comment]
V2.0 is in the works, and we've got a plan to address this. Most parameters for the config builders in this suite can be grabbed from appSettings now, using the same ${settingName} syntax that is used for 'expand' mode in other config sections. The only catch is that if your config builder is being applied to appSettings, this mechanism will not work in expand mode. Also, settings added by builders later in the chain won't be available either obviously. Check out #42 to see if this works for your needs.

**Comment by martinoss** [comment]
Hi Stephen, this is exactly what I was looking for, thank you very much, this will simplify our build/release definitions significantly!
One thing I struggled over is, that the variable name must not contain a colon in it's key in appSettings. I will file a separate issue for this.

`<add key="system:VaultName" value="myvault-dev" />
`
