### ISSUE TITLE
Expand Tokens misses tokens

### ISSUE THREAD

**Issue by jo-me** [aspnet/MicrosoftConfigurationBuilders#4]
The "Expand" mode does not work for me currently because the recognition is too strict.

In the code I found the following regex that looks for tokens:
> \$\{(\w+)\}

Problematic is here that "\w" allows only alphanumerical characters and underscore. However, other characters such as dash (-) are allowed in keyvault secret names.

This could be helped by opening up the regex like this:
> \$\{(.+)\}

Or by having a regex per config source that uses the correct character set. 

I'm using VS 2017 15.6.5 with the preview2 of the config builder package.

**Comment by StephenMolloy** [comment]
#6

**Comment by StephenMolloy** [comment]
Fixed in pull #6.
