### ISSUE TITLE
How to use SimpleJsonConfigBuilder with .Net Full Framework Console App?

### ISSUE THREAD

**Issue by smadurange** [aspnet/MicrosoftConfigurationBuilders#40]
I have a Console App targeting .NET 4.7.1. I installed config builder using `Install-Package Microsoft.Configuration.ConfigurationBuilders.Json`. My `App.config` is:

```
<configuration>
  <configSections>
    <section name="configBuilders" type="System.Configuration.ConfigurationBuildersSection, System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" restartOnExternalChanges="false" requirePermission="false" />
  </configSections>
  <configBuilders>
    <builders>
    <add name="SimpleJson"
         jsonFile="config.json"
         optional="false"
         jsonMode="Sectional"
         type="Microsoft.Configuration.ConfigurationBuilders.SimpleJsonConfigBuilder, Microsoft.Configuration.ConfigurationBuilders.Json, Version=1.0.0.0, Culture=neutral" /></builders>
  </configBuilders>
```

And I have a file `config.json` which has property "Copy Always" set to `True`. `config.json` looks like:

```
{
  "AppConfiguration": {
    "Key1": "Value1",
    "Key2": "Value2",
    "Key3": "Value3"
  },
  "Connections": {
    "Key4": {
      "Key5": "MyConnectionStringHere"
    }
  }
}
```

Then, in my `main` method, I try to read a config value like:

`var config = ConfigurationManager.AppSettings["AppConfiguration"];`

However, it's always null. I tried the following:

1. Tried changing `jsonFile` to `~/config.json`;
2. Tried giving a very basic key-value (flat) json config while setting `jsonMode` to default value of flat;
3. I also tried a `config.json` file just like in the readme:
```
{
  "appSettings": {
    "setting1": "value1",
    "setting2": "value2",
    "complex": {
      "setting1": "complex:value1",
      "setting2": "complex:value2"
    }
  },

  "connectionStrings": {
    "mySpecialConnectionString": "Dont_check_connection_information_into_source_control"
  }
}
```

But, can't get the config to work. I couldn't find a clear, complete example. As far as I can see, the `config.json` file isn't even looked at at startup by the app.

**Comment by StephenMolloy** [comment]
The idea with the json builder is that it looks at the json file as a flat dictionary of key/value settings. Multiple levels of objects in json will get flattened by concatenating key names. So by default, if you used a standard SimpleJsonConfigBuilder in greedy mode with your config.json file on the <appSettings> section of your config, your app settings collection would  then contain the following key/value pairs:

- AppConfiguration:Key1 == Value1
- AppConfiguration:Key2 == Value2
- AppConfiguration:Key3 == Value3
- Connections:Key4:Key5 == MyConnectionStringHere

ConfigurationManager.AppSettings is a string/string collection. It's not possible to get a "config" object from that collection. You would have to read each key/value pair individually:
`string key1 = ConfigurationManager.AppSettings["AppConfiguration:Key1"]`
