### ISSUE TITLE
Secret retrieval in Strict mode not working for some secrets

### ISSUE THREAD

**Issue by jo-me** [aspnet/MicrosoftConfigurationBuilders#5]
In Strict mode, the config builder only retrieves 2 of ~15 secrets from the keyvault even though secrets with the names given in Web.config are present in the keyvault. 
I don't see any errors, the values just remain empty.

Are there any restrictions or naming conventions that apply here?

I'm using VS 2017 15.6.5 with the preview2 of the config builder package.

**Comment by StephenMolloy** [comment]
Fixed in #7.
