### ISSUE TITLE
SampleWeb runtime error

### ISSUE THREAD

**Issue by johnqxu1** [aspnet/MicrosoftConfigurationBuilders#51]
Using the SampleWeb in version 1.02,  got run time load error as below. I have tried to both sign or unsign key file but got the same error.   Is there a solution to this error?
Error is below from loading:
Parser Error Message: An error occurred loading a configuration file: Could not load file or assembly 'Microsoft.Configuration.ConfigurationBuilders.Environment, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name signature could not be verified. The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)
Source Error:
Line 21: 
=== Pre-bind state information ===
LOG: DisplayName = Microsoft.Configuration.ConfigurationBuilders.Environment, Version=1.0.0.0, Culture=neutral
(Partial)
WRN: Partial binding information was supplied for an assembly:
WRN: Assembly Name: Microsoft.Configuration.ConfigurationBuilders.Environment, Version=1.0.0.0, Culture=neutral | Domain ID: 2
WRN: A partial bind occurs when only part of the assembly display name is provided.
WRN: This might result in the binder loading an incorrect assembly.
WRN: It is recommended to provide a fully specified textual identity for the assembly,
WRN: that consists of the simple name, version, culture, and public key token.
WRN: See whitepaper http://go.microsoft.com/fwlink/?LinkId=109270 for more information and common solutions to this issue.
LOG: Appbase = file:///C:/DATA/Download/Microsoft/MicrosoftConfigurationBuilders-1.0.2/samples/SampleWebApp/
LOG: Initial PrivatePath = C:\DATA\Download\Microsoft\MicrosoftConfigurationBuilders-1.0.2\samples\SampleWebApp\bin

**Comment by johnqxu1** [comment]
Envrionment for this issue:
Window 7, VS 2017, Powershell version 5.0
Repeat issue:
Build as debug\release version. The run sampleWeb. IE show error during the start: Parser error message mentioned above

**Comment by StephenMolloy** [comment]
This is because the key file checked in with the project is used for test signing. The assemblies get a strong name, but you'll need to disable strong-name verification for them. (Or change your solution to fully sign them with your own key I guess.)
`sn.exe -Vr *,31bf3856ad364e35`
