### ISSUE TITLE
V2: Expanding token to draw from appSettings doesn't work with colon in key

### ISSUE THREAD

**Issue by martinoss** [aspnet/MicrosoftConfigurationBuilders#54]
Not really high priority, but I got an error when trying to draw the vaultName from appSettings when the key contained a colon like this:

`<add key="system:VaultName" value="myvault-dev" />`

```
  <configBuilders>
    <builders>
      <add name="AzureKeyVault" vaultName="${system:VaultName}" type="Microsoft.Configuration.ConfigurationBuilders.AzureKeyVaultConfigBuilder, Microsoft.Configuration.ConfigurationBuilders.Azure, Version=2.0.0.0, Culture=neutral" />
    </builders>
  </configBuilders>
```

**Comment by StephenMolloy** [comment]
As I'm sure you're aware, token expansion works using the same token pattern that is used when applying the config builder - in this case 'AzureKeyVault', which is admittedly a little self-referential - to the rest of configuration. The default token pattern for all these config builders is @"\$\{(\w+)\}", and I think this is where you're hitting your issue. Unfortunately, the ':' character does not match the '\w' character class. If you update the tokenPattern on your builder, you may have more sucess.

**Comment by StephenMolloy** [comment]
#63
