### ISSUE TITLE
Support colon mapping in key vault keys

### ISSUE THREAD

**Issue by twsouthwick** [aspnet/MicrosoftConfigurationBuilders#57]
Key vault does not support colons in the name but keys in app.config/web.config allow it. This is a request to have a way to map a string to another string. Not sure if this is possible via simple configuration or if it would require subclassing.

**Comment by StephenMolloy** [comment]
Mapping keys from the config file to arbitrary translations for lookup isn't really something that makes sense as those mappings could be - well, quite arbitrary. And would likely vary by the source provider of the config values as well. This is definitely something that should be handled by subclassing.

In V2 however, there are two opportunities for subclasses to get hands on keys: `ValidateKey(string)` before going to the config source for a value, and `UpdateKey(string)` after obtaining the value so the original key from the config file can be updated/overwritten. (Think removing a key vault version tag from the key name.)

The only problem there is that `ValidateKey(string)` is simply a yes/no function before going to the source. I suppose if we made the key a 'ref' parameter, it could be used to map the original key to an intermittent format before sending going to the config source.

**Comment by twsouthwick** [comment]
Yeah, that makes total sense. I had a hard time figuring out a good generic way to do it. What about adding a method `virtual string MapKey(string key) => key;` that could be overriden if needed?

**Comment by StephenMolloy** [comment]
That's essentially the same as the virtual `ValidateKey(string)`. There are definitely two distinct things that should get evaluated before using a key to lookup in a config source: 1) Map it, and 2) Validate it. And they both kind of play off each other. On the one hand, there is a KISS argument for separating the two into two virtual methods, as the function names and purposes are super clear. Otoh, I'm inclined to keep them intertwined in one virtual to prevent API overload and make the interplay between the two things simple/flexible.

I don't want to use a non-descript method name like PreProcessKey. Maybe `virtual bool MapAndValidate(ref string key)`? Or perhaps this boolean-AND-return-value pattern is more familiar as something like `virtual bool TryMapKey(string key, out string mappedKey)`? Though I think that might lose the suggestion that the function also does simple validation of a key even if no remapping is done. :/

I'm definitely open to suggestions on this.

**Comment by twsouthwick** [comment]
I'd prefer the two separate things and allow people to overload those if needed. This makes it much simpler if you only want to validate or only want to map; you don't have to think about the logic for the other case. If you wanted to keep them together I'd go with `virtual bool TryMapKey(string key, out string mappedKey)`.

**Comment by StephenMolloy** [comment]
#65

**Comment by twsouthwick** [comment]
Thanks!
