### ISSUE TITLE
AzureAppConfigurationBuilder - read filter parameters from AppSettings

### ISSUE THREAD

**Issue by radicalapps** [aspnet/MicrosoftConfigurationBuilders#58]
It would be great to be able to read labelFilter, and perhaps the other filters, from AppSettings. The ability to dynamically configure the App Configuration connection string is less useful without also being able to configure the related filters in the same way.
The scenario I want to support is where the App Configuration connection string and related filters are read from App Settings.
Could all filter vales be read using `UpdateConfigSettingWithAppSettings(tag)` instead of `config[tag]` to enable truly dynamic configuration?

**Comment by StephenMolloy** [comment]
#66
