### ISSUE TITLE
Expand mode example

### ISSUE THREAD

**Issue by akiller** [aspnet/MicrosoftConfigurationBuilders#69]
Hi,

Would it be possible to provide an example of using expand mode to override a custom section? I can't seem to grasp how it works from the readme.  I don't fully understand what _Any part of the raw xml string that matches the pattern ${token} is a candidate for token expansion_ means in regards to how I should set the environment variable (the builder I wish to use) to override a value. 

Does this mean I should set the environment variable to raw XML for each key as I want it to appear inside my custom section or something else? Could you provide an example of how it is formatted?

I currently have overriding working fine with strict/greedy mode, and have successfully implemented a custom SectionHandler to allow me to override my custom section, but it felt like a lot of work for something I think expand mode may more easily solve. It sounds like I've already done the hard version implementation so feel a little stupid for not being able to understand the easier option!

The custom section I'm trying to override is basically the same as appsettings, so I feel it should be very easy. MyCustomSection is implemented using its own [ConfigurationSection](https://docs.microsoft.com/en-us/dotnet/api/system.configuration.configurationsection) which I set-up to mimic the same key/value idea.

```xml
<MyCustomSection>
<add key="mycustomsection_key1", "mycustomsection_value1" />
...
</MyCustomSection>
```

The documentation for using a SectionHandler also seemed a little confusing - I think mostly because the [ConfigurationSection](https://docs.microsoft.com/en-us/dotnet/api/system.configuration.configurationsection) I was already using [(NameValueFileSectionHandler)](https://docs.microsoft.com/en-us/dotnet/api/system.configuration.namevaluefilesectionhandler) - which has been working great for us for years, wasn't compatible with ConfigurationSection required by the SecionHandler:

```xml
  <configSections>
    <section name="MyCustomSection" type="System.Configuration.NameValueFileSectionHandler,System, Version=1.0.3300.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
  </configSections>
```

Would you accept a pull request with a more detailed example if I wrote one to help people out?

Thanks

**Comment by StephenMolloy** [comment]
Progress on the actual RTM release of version 2 of these config builders is moving pretty slowly in fits and starts as my attentions get pulled in different directions. But there are two ways you could consider to address your particular scenario.

1) Use 'Expand' mode on your custom section as you suggest. I can certainly update (or accept a PR) the readme with a better explanation and sample* on how to use this mode. Or,
2) Write and register a new (section handler)[https://github.com/aspnet/MicrosoftConfigurationBuilders#section-handlers] that knows how to work with key/value pairs in your custom section. In V2, section handlers are how all sections are processed by these config builders. We just wire up section handlers for AppSettings and ConnectionStrings by default as those are the common scenario.

* - A quick note on 'Expand' mode. It's pretty simple really. The .Net Framework gives ConfigurationBuilders two chances to process configuration when building up config objects. The first chance receives a simple string of the raw xml contained in the config section. The second chance gets to operate on the ConfigurationSection object that results after parsing the xml.

If your builder is set in expand mode, then it will operate in phase 1 on the raw xml __string__. So, if you had a custom section like this:
```xml
<MyCustomSection configBuilders="environment">
    <add key="custom_key" value="${custom_value}" />
    ${full_add_remove_element}
</MyCustomSection>
```

The `environment` config builder would look for environment variables named 'custom_value' and 'full_add_remove_element' and directly replace the tokens in that xml string with the environment variable values. (Or leave the token as is if there is no matching environment variable.) Assuming your environment has
```
custom_value=42
full_add_remove_element=<remove key="custom_key"/>
```
then the resulting xml that gets used to build the config object would look like this:
```xml
<MyCustomSection configBuilders="environment">
    <add key="custom_key" value="42" />
    <remove key="custom_key"/>
</MyCustomSection>
```

**Comment by akiller** [comment]
Hi Steve, 

Firstly, apologies for the very slow reply - being pulled in lots of directions is happening over the pond here too. I can't promise anything but if I get chance I will look at submitting a PR to help out.

Thank you very much for the explanation. I think that covers what I need to get my head around using it. I think that's pretty much as I expected it to work which is great. It looks easy once you know how!

Regards,
Andrew

**Comment by StephenMolloy** [comment]
#95

**Comment by diff-by-default** [comment]
> Progress on the actual RTM release of version 2 of these config builders is moving pretty slowly in fits and starts as my attentions get pulled in different directions. But there are two ways you could consider to address your particular scenario.
> 
> 1. Use 'Expand' mode on your custom section as you suggest. I can certainly update (or accept a PR) the readme with a better explanation and sample* on how to use this mode. Or,
> 2. Write and register a new (section handler)[https://github.com/aspnet/MicrosoftConfigurationBuilders#section-handlers] that knows how to work with key/value pairs in your custom section. In V2, section handlers are how all sections are processed by these config builders. We just wire up section handlers for AppSettings and ConnectionStrings by default as those are the common scenario.
> 
> * * A quick note on 'Expand' mode. It's pretty simple really. The .Net Framework gives ConfigurationBuilders two chances to process configuration when building up config objects. The first chance receives a simple string of the raw xml contained in the config section. The second chance gets to operate on the ConfigurationSection object that results after parsing the xml.
> 
> If your builder is set in expand mode, then it will operate in phase 1 on the raw xml **string**. So, if you had a custom section like this:
> 
> ```
> <MyCustomSection configBuilders="environment">
>     <add key="custom_key" value="${custom_value}" />
>     ${full_add_remove_element}
> </MyCustomSection>
> ```
> 
> The `environment` config builder would look for environment variables named 'custom_value' and 'full_add_remove_element' and directly replace the tokens in that xml string with the environment variable values. (Or leave the token as is if there is no matching environment variable.) Assuming your environment has
> 
> ```
> custom_value=42
> full_add_remove_element=<remove key="custom_key"/>
> ```
> 
> then the resulting xml that gets used to build the config object would look like this:
> 
> ```
> <MyCustomSection configBuilders="environment">
>     <add key="custom_key" value="42" />
>     <remove key="custom_key"/>
> </MyCustomSection>
> ```

Is this functionality still available? I know Expand mode has been renamed to Token mode (most msoft docs outside of this specific repo still mention Expand mode everywhere). The example that got added to the README.md out of this Issue seems to have been since removed and I can't get this to work for the life of me. 

A barebones example with any sort of ${token} replacement involving anything that isn't a Key= or Value= seems to just throw "section cannot contain CDATA or text" or other generic errors and I can't find enough documentation on the Token expansion mode to figure out what I'm missing. I've tried using this specific example as a starting point and it's hard to tell if I'm missing a piece or this functionality just doesn't exist anymore since the docs have changed again.

**Comment by StephenMolloy** [comment]
Nope, it's gone.  As you probably noticed, [it's been replaced by `Token` mode](https://github.com/aspnet/MicrosoftConfigurationBuilders#v3-updates) which is _similar_ but not exactly the same.

The reason `Expand` mode was removed is explained in the [FAQ - Why did you get rid of 'Expand' mode?](https://github.com/aspnet/MicrosoftConfigurationBuilders/blob/9036ac021c3cafab2370034ae88d7316e8f91ec1/docs/FAQ.md)
