### ISSUE TITLE
Accessing ConfigurationManager.ConnectionStrings when using AzureAppConfigurationBuilder results in indefinite hang

### ISSUE THREAD

**Issue by EvanMulawski** [aspnet/MicrosoftConfigurationBuilders#70]
## Overview

- ASP.NET MVC 5 / Web API 2 targeting net472
- Microsoft.Configuration.ConfigurationBuilders.AzureAppConfiguration 1.0.0-beta

Attempting to access `System.Configuration.ConfigurationManager.ConnectionStrings` results in an indefinite hang when using `Microsoft.Configuration.ConfigurationBuilders.AzureAppConfigurationBuilder`.

There is no issue when attempting to access `System.Configuration.ConfigurationManager.AppSettings`.

## Reproduction

https://github.com/EvanMulawski/AzureAppConfigurationBuilderConnectionStringsIssue

### Configuration

Provide App Configuration connection string in web.config for both builders.

### Testing Endpoints

```
/api/appsettings => OK
/api/connectionstrings => NOT OK
```

**Comment by StephenMolloy** [comment]
I haven't had a chance to look at the repro yet. But off the top of my head, this could be related to configuration folding back onto itself in an endless recursive loop. I don't have this branch merged or a nuget package for it. But could you try pulling this branch down and building it and using it's config builders in your repro project? Hopefully that would shed light on exactly what is happening.

https://github.com/aspnet/MicrosoftConfigurationBuilders/tree/Handle_Recursion

**Comment by EvanMulawski** [comment]
@StephenMolloy I will try that.

I should also note that this issue does not occur in a net472 console app - it works as expected. Maybe something specific with web configuration?

**Comment by EvanMulawski** [comment]
@StephenMolloy Are `Microsoft.Azure.AppConfiguration.AzconfigClient` and `Microsoft.Azure.AppConfiguration.ManagedIdentityConnector` available on a preview/CI feed?

**Comment by StephenMolloy** [comment]
Ahh, yes, I think they are. They should be published as binaries within the existing nupkg for AzureAppConfiguration 1.0.0-beta.

**Comment by EvanMulawski** [comment]
@StephenMolloy Doesn't look like this branch solved the issue.

Using my repro project, I uninstalled the packages, referenced the built binaries, and disabled strong name verification for them. No changes to web.config (since default `recursionCheck` is `Throw`). Same result - app settings load fine, connection string access causes an indefinite hang.

**Comment by StephenMolloy** [comment]
I've had some time to look at this this week. It looks like there is the potential for deadlock with async code in the packaged App Configuration client SDK that we're using.

The reason the SDK was packaged in our beta release is because it was not intended to be the official released SDK for this Azure feature, and it would be later replaced by an official nuget reference to an SDK from the Azure SDK team. I'll work on making this update and hopefully releasing an RC soon (depending on how people feel about including the recursion branch I pointed you to earlier in this issue.)

**Comment by StephenMolloy** [comment]
Oops, I forgot to update this before changing focus to other projects. This was indeed a bug in the internal SDK. It should go away with the official public SDK for accessing AppConfiguration. That is currently in preview. I'll hopefully be releasing an beta/rc using the "official" SDK this month. But RTM won't come until after the SDK also RTM's. :/ (I'll come back and resolve this when the beta/rc with the new SDK is available.)

**Comment by StephenMolloy** [comment]
Fixed with #88
