### ISSUE TITLE
Should we use AzureKeyVaultConfigBuilder over KeyVault references ?

### ISSUE THREAD

**Issue by TechWatching** [aspnet/MicrosoftConfigurationBuilders#76]
When deploying our app in an Azure App Service, we have the option to use  App Service [Keyvault references](https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references). It is something that I used first with Azure Functions but that works very well with App Service as well. 

So I was wondering what is the best solution between using AzureKeyVaultConfigurationBuilder and Keyvault references. Is there a recommandation from Microsoft ?

**Comment by StephenMolloy** [comment]
I don't believe we have any official recommendation. If all you want is to inject appSettings from Key Vault into your app - and your app is in Azure - then either option works well. App Service probably requires a little less legwork in that you need to add configuration to get the config builder to work.

But if you app is not running in Azure, or if you want to inject settings from Key Vault into other sections of config besides AppSettings… then you'll want to use a config builder. They are generally more flexible, portable, and powerful... if you need that. Simple appSetting replacement is fine for many cases.
