### ISSUE TITLE
V2 Using Amazon SSM Parameter Store

### ISSUE THREAD

**Issue by HaroonSaid** [aspnet/MicrosoftConfigurationBuilders#78]
I am developing a custom provider to for AWS System Manager Parameter Store.
I am running into an issue with LazyInitialization:
```
        protected override void LazyInitialize(string name, NameValueCollection config)
        {
            Debug.WriteLine($"Entry:{nameof(ParameterStoreConfigBuilder)}:{nameof(LazyInitialize)}");
            Optional = true;
            base.LazyInitialize(name, config);
            string env = UpdateConfigSettingWithAppSettings(envTag);
            if (string.IsNullOrWhiteSpace(env))
                throw new ArgumentException($"environment must be specified with the '{envTag}' attribute.");
            environment = env;
            string appName = UpdateConfigSettingWithAppSettings(appNameTag);
            if (string.IsNullOrWhiteSpace(appName))
                throw new ArgumentException($"appName must be specified with the '{appNameTag}' attribute.");
            this.appname = appName;
            this.tenant = UpdateConfigSettingWithAppSettings(tenantTag);
            client = new AmazonSimpleSystemsManagementClient();
            Debug.Assert(client != null);
            Debug.WriteLine($"Exit:{nameof(ParameterStoreConfigBuilder)}:{nameof(LazyInitialize)}");
}
```
As soon we try to create a new client = new AmazonSimpleSystemsManagementClient();
The underlying code wants to read app.config that immediately causes `GetValue(string key)` to be fired, however, the client has not been created yet.
Is there a way to suppress firing `GetValue(string key)` until LazyInitialization has completed.

The GetValue 
```
        public override string GetValue(string key)
        {
            var name = $"/{environment}/{appname}/{key.Replace(':', '/')}";
            Debug.WriteLine($"Entry:{nameof(ParameterStoreConfigBuilder)}:{nameof(GetValue)}:{name}");
            Debug.Assert(client != null);
            if (client == null)
                return null;
            var request = new GetParameterRequest
            {
                Name = name,
                WithDecryption = true
            };
            var response = client.GetParameter(request);
            var parameter = response.Parameter;
            var value = parameter.Type == ParameterType.SecureString ? "*****" : parameter.Value;
            Debug.WriteLine($"Exit:{nameof(ParameterStoreConfigBuilder)}:{nameof(GetValue)}:{name}={value}");
            return value;
        }
```

**Comment by StephenMolloy** [comment]
I'm not sure there is an ideal answer here. Recursion isn't something we can handle gracefully at this level. It ideally should be baked into the .Net Framework... but that ship has sailed.

I did try a rough attempt at detecting/handling recursion, but never got any feedback from the one customer who had raised the issue. It's unlikely to make it into the 2.0 release at this point, since it would be a pretty substantial PR this late. If you want to give it a look and see if it makes sense and works for your scenario and do more testing than just me poking at it... it's still risky at this point, but I wouldn't absolutely rule it out.

The branch of my rough attempt is [Handle_Recursion](https://github.com/aspnet/MicrosoftConfigurationBuilders/tree/Handle_Recursion)

**Comment by HaroonSaid** [comment]
Yes, I agree, after trying a few different workarounds, there isn't a solution without changing the underlying .NET Framework API.  The only way I can see the `MicrosoftConfigurationBuilders` working is to build it as `NETSTANDARD2.0` and somehow anyone that calls a 3rd party library to be NETSTANDARD compatible such that it doesn't use code that uses AppSettings

**Comment by andremantaswow** [comment]
If anyone else gets here... what we ended up doing was setup a lambda that exposes an API that calls the parameter store (eg new up a AmazonSimpleSystemsManagementClient and calling the methods)
This way we can just call this external API from the LazyInitialize method (or similar) and get everything we need
