### ISSUE TITLE
[BUG] AzureServiceTokenProviderException when using AzureKeyVaultConfigurationBuilder

### ISSUE THREAD

**Issue by TechWatching** [aspnet/MicrosoftConfigurationBuilders#79]
When using AzureKeyVaultConfigurationBuilder I sometimes have an AzureServiceTokenProviderException :
![AzureServiceTokenProviderException](https://user-images.githubusercontent.com/15186176/66908385-44239580-f00b-11e9-8bbb-c883c19f1dca.png)
![MsiAccessTokenProvider](https://user-images.githubusercontent.com/15186176/66907976-9e702680-f00a-11e9-92b4-96934b2b5f26.png)

It happens whitout changes relative to keyvault, although previous runs works fine.
My current workaround is to delete the .vs folder which makes it works again.

It seems the token or something else is cached in the .vs folder which makes it crash.

I have access to several Azure tenants with the user I am connected with in Visual Studio, and the tenant from where I am retrieving secrets from has MFA on it.

**Comment by StephenMolloy** [comment]
#88
