### ISSUE TITLE
AzureAppConfigurationBuilder - cannot read values

### ISSUE THREAD

**Issue by marco-gallinari** [aspnet/MicrosoftConfigurationBuilders#82]
Hello, 

I'm trying to add an AzureAppConfigurationBuilder to an ASP.NET MVC 4 app recently upgraded to .net Framework 4.7.2.

I was able to add an EnvironmentConfigBuilder properly, but I'm struggling to read values from Azure App Configuration service.

I installed the following packages from nuGet:

```
  <package id="Microsoft.Configuration.ConfigurationBuilders.AzureAppConfiguration" version="1.0.0-beta" targetFramework="net472" />
  <package id="Microsoft.Configuration.ConfigurationBuilders.Base" version="2.0.0-beta" targetFramework="net472" />
  <package id="Microsoft.Configuration.ConfigurationBuilders.Environment" version="2.0.0-beta" targetFramework="net472" />
  <package id="System.Configuration.ConfigurationManager" version="4.6.0" targetFramework="net472" />
```

And wrote this in my web.config:

```
   <configSections>
    ...
       <section name="configBuilders" type="System.Configuration.ConfigurationBuildersSection, System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" restartOnExternalChanges="false" requirePermission="false" />
    ...
   </configSections>

   <configBuilders>
      <builders>      
         <add name="AzureAppConfig" mode="Strict" connectionString="${AzureConfigStoreConnection}" type="Microsoft.Configuration.ConfigurationBuilders.AzureAppConfigurationBuilder, Microsoft.Configuration.ConfigurationBuilders.AzureAppConfiguration" />
         <add name="EnvironmentVariables" mode="Strict" type="Microsoft.Configuration.ConfigurationBuilders.EnvironmentConfigBuilder, Microsoft.Configuration.ConfigurationBuilders.Environment" />
      </builders>
   </configBuilders>
  
   <appSettings configBuilders="EnvironmentVariables,AzureAppConfig">
      <add key="AzureConfigStoreConnection" value="Undefined" />
      <add key="SampleKey" value="Undefined" />
      ...
  </appSettings>
```

With this configuration, application startup fails with the error:

```
Error in Configuration Builder 'AzureAppConfig'::GetValue(SampleKey)
```

If I configure Azure AppConfiguration connectionString directly in the builder, the app starts fine, but when inspecting the value of System.Configuration.ConfigurationManager.AppSettings["SampleKey"] I find the value "Undefined", and not the one I expect to read from Azure.

System.Configuration.ConfigurationManager.AppSettings["AzureConfigStoreConnection"] instead is properly taken from environment variables.

Did I forget something?

**Comment by StephenMolloy** [comment]
Your config snippits look good. And if you are correct that AzureConfigStoreConnection is getting replaced in appSettings correctly, then I suspect you are possibly hitting a network/firewall issue between your app and your config store. Or you might not have the right permissions granted on your config store. Being a service that is still in development, some of the requirements for accessing the service have been in flux.

Shortly after the holiday break we will have an RC version up on nuget.org. The RC does away with the `connectionString` option as it is no longer supported by the official SDK for accessing Azure AppConfiguration. Use the `endpoint` attribute instead and let the magic of Managed Service Identity/Azure.Identity do the rest. With this new SDK version, you will need to add the "App Configuration Data Reader" role to your app to give it the correct permissions for reading from the config store.

**Comment by marco-gallinari** [comment]
Hi @StephenMolloy, thank you for the anticipations.

Just a note: I don't think the issue could be related to networking, as it rose on an Azure AppService deployment, too. 
We found a workaround by defining a custom builder that simply reads the AppConfig, and it's working fine.

We'll update the upcoming RC to test if the issue is gone.

**Comment by byounge** [comment]
Hey @marco-gallinari  or others hitting this issue - this issue occurs if the environment variable is not set as a permanent variable (use command line command 'setx') at the time that Visual Studio is launched.  Env variables get loaded when the session begins, so if after VS is running you make a change to an Env variable via powershell or the cmd prompt, VS will not get this new value.  I searched and have not found a way to tell VS to reload the Env variables without closing and restarting it.
