### ISSUE TITLE
Roadmap for Azure App Configuration

### ISSUE THREAD

**Issue by giggio** [aspnet/MicrosoftConfigurationBuilders#83]
I couldn't find the roadmap for Azure App Configuration, not on docs, not on this repo. It is currently marked as beta. Do we know when this lib will RTM?

**Comment by StephenMolloy** [comment]
The roadmap is dependent on the roadmap for the service itself, as well as the official Azure SDK for accessing config stores. With respect to this repo, I hope to have an 'RC' update for App Configuration in the next week or two (along with 2.0 RTM for all other builders.) This 'RC' is not officially RTM, but I don't expect any big changes after 'RC' other than updating dependencies to the official SDK bits.

For 'RTM', the service itself will not GA until January - Azure/AppConfiguration-Announcements#2
I do not know the roadmap for the official SDK though. Once that dependency reaches RTM, we can take the preview tag off of this builder package as well.
