### ISSUE TITLE
Using Section Handlers

### ISSUE THREAD

**Issue by lukealvarez** [aspnet/MicrosoftConfigurationBuilders#86]
Hi Steve,
I started using Configuration Builders and get some issues to create a custom handler for a custom section. I read the documentation and I can't figure out how to implement the handlers.
I created a custom handler and then setup it in the web.config. Could you help me to figure out how handlers works?  

How I setup the handler on my web.config:
![image](https://user-images.githubusercontent.com/17647094/70824335-d0aac400-1dc0-11ea-9347-79b846a8e791.png)

The custom section
![image](https://user-images.githubusercontent.com/17647094/70824400-f3d57380-1dc0-11ea-8e75-c0ba2e988414.png)

My custom handler:
![image](https://user-images.githubusercontent.com/17647094/70823923-c76d2780-1dbf-11ea-9312-d04a35782e0d.png)

Thanks!

**Comment by StephenMolloy** [comment]
Off the top of my head, I can see a couple things that might be getting in your way. The first is when you add your new section handler... you specify a type name, but not an assembly. I believe this should result in a runtime error that you would definitely notice.

The second issue is that you didn't apply any config builders to your <serviceSettings> section. Without tagging the section with `configBuilder=`, loading that section will never even enter into the config builder system.

Lastly, the full-framework .Net config system only loads sections on demand. Presumably you will have some code in your test project that loads the 'serviceSettings' section.
